learning-process/ppc-2023-mpi

- tasks/task_1/kulikov_a_min_in_matr/CMakeLists.txt
- tasks/task_1/kulikov_a_min_in_matr/main.cpp
- tasks/task_1/kulikov_a_min_in_matr/min_in_matr.cpp
- tasks/task_1/kulikov_a_min_in_matr/min_in_matr.h
Решалась задача нахождения минимальных значений для строк матрицы. Как ответ и средство проверки использовался индекс соответствующего элемента. В ходе решения каждому процессу выделялось определённое количество строк, равное, скажем, `delta`. Процессы искали минимум для предоставленных им строк и возвращали массив размерности `delta`, содержащий индексы минимумов. Затем эти массивы собирались в результирующий на 0 процессе. При распределении строк также учитывалось, что их количество может и не делиться на `world.size()` - остаток отдаётся на обработку процессу 0.
> Куликов Артём. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.

- tasks/task_1/ivanov_int_tr/CMakeLists.txt
- tasks/task_1/ivanov_int_tr/int_tr.cpp
- tasks/task_1/ivanov_int_tr/int_tr.h
- tasks/task_1/ivanov_int_tr/main.cpp
Решалась задача подсчета интеграла функции с помощью метода трапеций. В качестве проверки правильности решения использовалось значение, которое было получено с помощью сервиса [desmos](https://www.desmos.com/calculator?lang=ru). Это значение сверялось с посчитанным так, чтобы погрешность в измерениях была меньше чем 0.00001. Еще в качестве входных данных использовались границы интегрирования(`a` и `b`) и число разбиений - `N`. 
Между процессами распределялись участки интегрирования в равном количестве. Исключение составлял только самый последний процесс, который мог интегрировать больший участок, если изначальный отрезок нельзя было разделить на равное число шагов. 
> **Пример**: если длина интервала 10 единиц, а процессов только 3, то первым двум процессам уйдут интервалы длиной 3 …
> Иванов Никита. Задача 1. Вариант 20.  Интегрирование – метод трапеций.

- tasks/task_1/zakharov_a_min_of_vector_elements/CMakeLists.txt
- tasks/task_1/zakharov_a_min_of_vector_elements/main.cpp
- tasks/task_1/zakharov_a_min_of_vector_elements/min_vector_elements.cpp
- tasks/task_1/zakharov_a_min_of_vector_elements/min_vector_elements.h
Необходимо найти минимальное значение в векторе. Для этого процессам выделяется определенное количество элементов вектора, и каждый процесс находит минимум среди переданных ему элементов.  Затем среди найденных элементов выбирается наименьший, который и будет являться минимальным элементом в исходном векторе. 
Если количество элементов исходного вектора не делится поровну между процессами, то оставшиеся элементы отдаются нулевому процессу.
> Захаров Артем. Задача 1. Вариант 4. Минимальное значение элементов вектора.

- tasks/task_1/vanushkin_d_rect_integration/CMakeLists.txt
- tasks/task_1/vanushkin_d_rect_integration/main.cpp
- tasks/task_1/vanushkin_d_rect_integration/rectangle_integration.cpp
- tasks/task_1/vanushkin_d_rect_integration/rectangle_integration.h
Требуется вычислить приближённое значение интеграла, используя метод прямоугольников.
В своей задаче я использовал метод средних прямоугольников.
Функция принимает на вход левую, правую границу и шаг `delta x`
На каждой итерации вычисляется площадь прямоугольника:
`h = f( (x + (x + delta x)) / 2 )`, где  `f(x)` - подынтегральная функция
`w = delta x`
В счётчик добавляем площадь `s = wh`
> Ванюшкин Дмитрий. Задача 1. Вариант 19. Интегрирование – метод прямоугольников.

- tasks/task_2/zakharov_a_star_topology/CMakeLists.txt
- tasks/task_2/zakharov_a_star_topology/main.cpp
- tasks/task_2/zakharov_a_star_topology/star_topology.cpp
- tasks/task_2/zakharov_a_star_topology/star_topology.h
Сеть `"Звезда"` - это сеть, в которой все процессы соединены только с одним главным процессом `root`.  Процесс не являющийся главным назовем `child`. Передача данных от `child` к `child` возможна только через  `root` процесс. Так как `root` связан со всеми остальным процессами, то для передачи данных между любыми двумя процессами потребуется максимум один процесс посредник, которым и будет являться `root`.
Для передачи данных между процессами используются функции `send` и `recv`.
> Захаров Артем. Задача 2. Вариант 12. Топология сети передачи данных "Звезда".

- README.md
- tasks/task_2/ivanov_gauss_lent_horiz/CMakeLists.txt
- tasks/task_2/ivanov_gauss_lent_horiz/gauss_lent_horiz.cpp
- tasks/task_2/ivanov_gauss_lent_horiz/gauss_lent_horiz.h
- tasks/task_2/ivanov_gauss_lent_horiz/main.cpp
Пусть у нас есть система алгебраических уравнений, которая записана в матричном виде. Метод Гаусса состоит из двух шагов:
+ **Прямой ход** - приведение СЛАУ к треугольному виду
+ **Обратный ход** - начиная с последней, находятся все неизвестные
Между процессами распределяются строки матрицы. За это отвечает функция `get_slice`.
> Пример. Пусть у нас есть система уравнений из трех 3-х строк и 2 процесса, тогда первому процессу отойдут строки **1** и **3**, а второму - **2**
Основная функция для передачи сообщений это `broadcast`. В прямом ходе через broadcast рассылается строка системы, которая будет вычитаться из других. В обратном ходе через этот механизм распространяются найденные переменные.
> Иванов Никита. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.

- tasks/task_2/soloninko_a_gauss_horizontal/CMakeLists.txt
- tasks/task_2/soloninko_a_gauss_horizontal/Gauss.cpp
- tasks/task_2/soloninko_a_gauss_horizontal/Gauss.h
- tasks/task_2/soloninko_a_gauss_horizontal/main.cpp
Нужно решить систему алгебраических уравнений, записанных в виде матрицы. Алгоритм Гаусса состоит из двух функций: `gaussian_elimination` и `gaussian_substitution`.
`gaussian_elimination` приводит систему линейных уравнений к треугольному виду.
`gaussian_substitution` находит сами неизвестные, которые надо было найти. 
В ленточном горизонтальном варианте алгоритма Гаусса мы рассылаем строки матрицы по процессам через функцию `MPI_Bcast`.
Для проверки результата, мы предполагаем, что правая часть матрицы будет равна левой с точностью до 0.0001.
> Солонинко Андрей. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.

- tasks/task_1/kostanyan_a_sum_values_by_rows_matrix/CMakeLists.txt
- tasks/task_1/kostanyan_a_sum_values_by_rows_matrix/alg.cpp
- tasks/task_1/kostanyan_a_sum_values_by_rows_matrix/alg.h
- tasks/task_1/kostanyan_a_sum_values_by_rows_matrix/main.cpp
Эта программа представляет собой реализацию алгоритма для вычисления суммы значений по строкам матрицы с использованием MPI. Программа содержит следующие функции:
1. `RandomMatrix` (int rows, int cols): 
- Создает случайную матрицу указанного размера (строки x столбцы).
2. `calculateRowSums` (const std::vector<int>& matrix, int rows, int cols):
- Вычисляет сумму значений по каждой строке в матрице.
3. `ParallelProcessing` (const std::vector<int>& matrix, int rows, int cols): 
- Эта функция использует MPI для распределенной обработки данных.
> Костанян Арсен. Задача 1. Вариант 11. Сумма значений по строкам матрицы.

- tasks/task_3/alexseev_d_Monte_Carlo_integral/CMakeLists.txt
- tasks/task_3/alexseev_d_Monte_Carlo_integral/Monte_Carlo_integral.cpp
- tasks/task_3/alexseev_d_Monte_Carlo_integral/Monte_Carlo_integral.h
- tasks/task_3/alexseev_d_Monte_Carlo_integral/main.cpp
Последовательное описание интегрирования методом Монте Карло:
1. Задать функцию foo(x), которую нужно проинтегрировать, и границы интегрирования [lowerLimit, upperLimit] по каждой переменной.
2. Задать количество точек pointsCount, которые будут генерироваться в процессе МК.
3. Сгенерировать pointsCount случайных чисел в промежутке [lowerLimit, upperLimit].
4. Подставить сгенерированные числа в функцию foo(x), вычислить значение функции в каждой точке.
5. Посчитать среднее значение функции по всем точкам: сумма всех значений функции / pointsCount.
6. Умножить среднее значение функции на объём пространства для получения приближенного значения интеграла.
В качестве референсов для тестов брал значения с сайта считающего интегралы. Из-за того что точность напрямую зависит от количества …
> Алексеев Данила, задача 3, вариант 10, вычисление многомерных интегралов методом Монте-Карло

- tasks/task_1/sadikov_d_dot_product/CMakeLists.txt
- tasks/task_1/sadikov_d_dot_product/dot_product.cpp
- tasks/task_1/sadikov_d_dot_product/dot_product.h
- tasks/task_1/sadikov_d_dot_product/main.cpp
Решалась задача нахождения скалярного произведения двух векторов.
В последовательной версии для этого использовалась функция inner_product из numeric.
В параллельной версии по процессам распределялось определенное кол-во элементов из обоих массивов. В случае, если длина векторов не делилась нацело на кол-во процессов, кол-во элементов, равное остатку от деления длины векторов на кол-во процессов, распределялось по 1 между соответствующим кол-вом процессов.
> Садиков Дамир. Задача 1. Вариант 9. Скалярное произведение векторов.

- tasks/task_2/sadikov_d_iterative_method/CMakeLists.txt
- tasks/task_2/sadikov_d_iterative_method/iterative_method.cpp
- tasks/task_2/sadikov_d_iterative_method/iterative_method.h
- tasks/task_2/sadikov_d_iterative_method/main.cpp
В качестве метода простой итерации был использован метод Якоби
> Садиков Дамир. Задача 2. Вариант 24. Метод простой итерации.

- tasks/task_1/polozov_v_max_values_by_column_matrix/CMakeLists.txt
- tasks/task_1/polozov_v_max_values_by_column_matrix/main.cpp
- tasks/task_1/polozov_v_max_values_by_column_matrix/max_values_by_column_matrix.cpp
- tasks/task_1/polozov_v_max_values_by_column_matrix/max_values_by_column_matrix.h
Для каждого столбца матрицы надо было найти максимальное значение в этом столбце. Разработана параллельная и последовательная версия алгоритма.
> Полозов Владислав. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы

- tasks/task_1/pozdnyakov_a_max_of_vector_elements/CMakeLists.txt
- tasks/task_1/pozdnyakov_a_max_of_vector_elements/main.cpp
- tasks/task_1/pozdnyakov_a_max_of_vector_elements/max_of_vector_elements.cpp
- tasks/task_1/pozdnyakov_a_max_of_vector_elements/max_of_vector_elements.h
Необходимо найти максимальный элемент в векторе. Для этого каждому процессу выделяется определённое количество элементов этого вектора, и каждый процесс находит среди них максимум. Затем среди этих элементов выделяется наибольший, который и является наибольшим в векторе. Если количество элементов не делиться между процессами поровну, то оставшиеся элементы отдаются нулевому процессу.
> Поздняков Василий. Задача 1. Вариант 3. Максимальное значение элементов вектора.

- tasks/task_3/pozdnyakov_a_cannon_multiply/CMakeLists.txt
- tasks/task_3/pozdnyakov_a_cannon_multiply/cannon_multiply.cpp
- tasks/task_3/pozdnyakov_a_cannon_multiply/cannon_multiply.h
- tasks/task_3/pozdnyakov_a_cannon_multiply/main.cpp
Алгоритм Кэннона — это распределённый алгоритм умножения матриц для двумерных сеток. 
Для подготовки данных на отправку процессорам для каждого нам нужно выбирать `k`, чтобы им не поступили к одни и тем же данные для вычислений. Данных выстраиваются в одномерный массив и отправляются процессам с помощью `scatterv`.
Каждый процесс получает свои подматрицы исходных матриц. Затем процесс перемножает их и прибавляет результат к своей итоговой матрице. После этого левая матрица циклически передается влево, а правая вверх по двумерной сетке процессов. Так продолжается `N` раз. где `N * N` - число процессов.
Затем результаты передаются корневому процессу с помощью `gatherv` и из них формируется конечная матрица.
> Поздняков Василий. Задача 3. Вариант 1. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона.

- tasks/task_1/volodin_e_matrix_max/CMakeLists.txt
- tasks/task_1/volodin_e_matrix_max/main.cpp
- tasks/task_1/volodin_e_matrix_max/matrix_max.cpp
- tasks/task_1/volodin_e_matrix_max/matrix_max.h
Программа решает задачу нахождения максимального значения элементов матрицы. Матрица хранится в виде вектора (по строкам).
Основной функцией здесь выступает findMax(), которая ищет максимум в заданной матрице, просто перебирая все элементы матрицы.
Функция findMaxParallel() выступает параллельным аналогом функции findMax(). В аналоге сначала определяется размер частей матрицы, которые будут выделены каждому процессу. Кроме того, определяется остаток элементов, которые не достались никакому процессу. Этот остаток возьмет на себя основной процесс. 
Затем определяется размер посылаемых данных, смещение в векторе, и каждому процессу с помощью функции MPI_Scatterv() выделяется часть матрицы, в которой он должен найти локальный максимум. Локальный максимум ищется с помощью функции findMax(). …
> Володин Евгений. Задача 1. Вариант 13. Максимальное значение элементов матрицы.

- tasks/task_2/volodin_e_dining_philosophers/CMakeLists.txt
- tasks/task_2/volodin_e_dining_philosophers/main.cpp
- tasks/task_2/volodin_e_dining_philosophers/philosophers.cpp
- tasks/task_2/volodin_e_dining_philosophers/philosophers.h
Классическая постановка задачи звучит так: пять безмолвных философов сидят вокруг круглого стола, перед каждым философом стоит тарелка спагетти. На столе между каждой парой ближайших философов лежит по одной вилке.
Каждый философ может либо есть, либо размышлять. Приём пищи не ограничен количеством оставшихся спагетти — подразумевается бесконечный запас. Тем не менее, философ может есть только тогда, когда держит две вилки.
Вопрос задачи заключается в том, чтобы разработать модель поведения (параллельный алгоритм), при котором ни один из философов не будет голодать, то есть будет вечно чередовать приём пищи и размышления.
В представленной программе цикл "жизни философа" представлен в единственном экземпляре: каждый из философов сначала подумает, потом поест, а потом завершит свое …
> Володин Евгений. Задача 2. Вариант 3. "Обедающие философы".

- tasks/task_2/lesnikov_hypercube/CMakeLists.txt
- tasks/task_2/lesnikov_hypercube/hypercube.cpp
- tasks/task_2/lesnikov_hypercube/hypercube.h
- tasks/task_2/lesnikov_hypercube/main.cpp
Необходимо реализовать топологию передачи данных "гиперкуб".
Алгоритм:
1) Создаем матрицу смежности гиперкуба
2) Через BFS находим путь между двумя процессами и формируем 2 вектора: expectations - от кого ждем данные, transitions - кому необходимо переслать данные.
3) Выполняем следующие действия в зависимости от ранга текущего процесса:
3.1) Отправляем данные с помощью send ожидающему процессу (если находимся в source процессе)
3.2) Принимаем данные с помощью recv от ожидаемого процесса (если находимся в dest процессе)
3.3) Выполняем по порядку 3.2 и 3.1 (если промежуточный процесс)
> Лесников Никита. Задача 2. Вариант 14. Гиперкуб 

- tasks/task_2/pivovarov_a_producer_consumer/CMakeLists.txt
- tasks/task_2/pivovarov_a_producer_consumer/main.cpp
- tasks/task_2/pivovarov_a_producer_consumer/producer_consumer.cpp
- tasks/task_2/pivovarov_a_producer_consumer/producer_consumer.h
Программа решает задачу "производители-потребители". Эта задача моделирует взаимодействие множества производителей, которые генерируют данные, и множества потребителей, которые потребляют эти данные. Обе версии алгоритма создают буфер для обмена данными между производителями и потребителями.
Последовательная версия: Производители и потребители выполняются последовательно в рамках одного процесса. Буфер обеспечивает синхронизацию между производителями и потребителями.
Параллельная версия: Работа производителей и потребителей распределена между процессами MPI, позволяя параллельно выполнять операции производства и потребления данных. Синхронизация между процессами обеспечивается использованием MPI_Barrier.
> Пивоваров Алексей. Задача 2. Вариант 1. Задача «Производители-потребители». 

- tasks/task_3/pivovarov_a_shell_sort_simple_merge/CMakeLists.txt
- tasks/task_3/pivovarov_a_shell_sort_simple_merge/main.cpp
- tasks/task_3/pivovarov_a_shell_sort_simple_merge/shell_sort_simple_merge.cpp
- tasks/task_3/pivovarov_a_shell_sort_simple_merge/shell_sort_simple_merge.h
Последовательный алгоритм:
Используем сортировку Шелла для последовательной обработки массива.
Проходим через массив с постепенным уменьшением интервала (gap) и применяем сортировку вставкой для каждого интервала.
Параллельный алгоритм:
Распределяем массив между процессами с использованием MPI и MPI_Scatter.
Каждый процесс локально сортирует свой подмассив с помощью сортировки Шелла.
Собираем отсортированные подмассивы на основном процессе с использованием MPI_Gather.
Основной процесс выполняет слияние отсортированных подмассивов с использованием функции merge.
> Пивоваров Алексей. Задача 3. Вариант 16. Сортировка Шелла с простым слиянием.

- tasks/task_3/khodyrev_f_simpson_method/CMakeLists.txt
- tasks/task_3/khodyrev_f_simpson_method/main.cpp
- tasks/task_3/khodyrev_f_simpson_method/simpson_method.cpp
- tasks/task_3/khodyrev_f_simpson_method/simpson_method.h
В данной задаче мною был реализован последовательный и параллельный алгоритмы, вычисляющие n-мерные интегралы методом Симпсона. Суть метода заключается в том, что мы делим область интегрирования на так называемую "сетку" и далее находим сумму значений функций в каждой точке сетке по формуле Симпсона. В параллельной версии "сетка" равномерно распределяется между имеющимися процессами (если количество точек на "сетке" не делится на количество процессов без остатка, то оставшиеся точки отходят процессу с наивысшим рангом). 
Для проверки работоспособности данной программы мною были написаны пять тестов (вычисление одномерного интеграла, вычисления двумерного интеграла, вычисления двумерного интеграла с другой областью интегрирования, вычисления трехмерного интеграла, вычисление трехмерного …
> Ходырев Федор. Задача 3. Вариант 9. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

- tasks/task_1/Kazantsev_e_near_neighbor_el/CMakeLists.txt
- tasks/task_1/Kazantsev_e_near_neighbor_el/main.cpp
- tasks/task_1/Kazantsev_e_near_neighbor_el/main_v.cpp
- tasks/task_1/Kazantsev_e_near_neighbor_el/near_neighbor_el.cpp
- tasks/task_1/Kazantsev_e_near_neighbor_el/near_neighbor_el.h
Реализовано 3 функции.
1) Генерирует вектор случайных чисел.
2) Выполняет поиск ближайшего соседа по абсолютной величине SequentialCount
3) Выполняет поиск на различных процессах parallelCount
> Казанцев Евгений. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.

- tasks/task_2/kazantsev_e_mul_tape_matrix/CMakeLists.txt
- tasks/task_2/kazantsev_e_mul_tape_matrix/main.cpp
- tasks/task_2/kazantsev_e_mul_tape_matrix/mul_tape_matrix.cpp
- tasks/task_2/kazantsev_e_mul_tape_matrix/mul_tape_matrix.h
Организовано перемножение матриц последовательно и параллельно/
Ленточная горизонтальная схема А, вертикальное В.
Использованы такие функции MPI как: Bcast, Send, Recv, Gather.
В качестве данных использованы матрицы N * N, поддерживается так же перемножение матриц с отличным числом столбцов и строк.
> Казанцев Евгений. Задача 2. Вариант 18. Ленточная горизонтальная схема А, вертикальное В

- tasks/task_1/petrov_m_max_of_matrix_elements/CMakeLists.txt
- tasks/task_1/petrov_m_max_of_matrix_elements/main.cpp
- tasks/task_1/petrov_m_max_of_matrix_elements/max_of_matrix_elements.cpp
- tasks/task_1/petrov_m_max_of_matrix_elements/max_of_matrix_elements.h
Нахождение максимального значения элементов матрицы. Матрица хранится в виде вектора. Функция init_matrix инициализирует матрицу случайными элементами. Функция getSequentialOperations представляет последовательный поиск максимума. Функция getParallelOperations - это параллельный поиск максимума, где распределение наборов чисел происходит следующим образом: число элементов матрицы/ количество процессов. Если есть остаток, то его получает нулевой процесс. Каждый процесс ищет локальный максимум в своей строке (наборе чисел), после чего из них выбирается наибольший.
> Петров Максим. Задача 1. Вариант 13. Максимальное значение элементов матрицы. 

- tasks/task_3/petrov_m_dense_matr_cannon/CMakeLists.txt
- tasks/task_3/petrov_m_dense_matr_cannon/dense_matr_cannon.cpp
- tasks/task_3/petrov_m_dense_matr_cannon/dense_matr_cannon.h
- tasks/task_3/petrov_m_dense_matr_cannon/main.cpp
Ускорение с помощью параллельного алгоритма колеблется в районе 4 (всегда больше 1). Чем больше размер матрицы, тем больше ускорение. Следовательно параллельный алгоритм эффективен. 
Новая группа процессов создается для обеспечения работы только с теми процессами, которые реально участвуют в вычислениях.
> Петров Максим. Задача 3. Вариант 1. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона.

- tasks/task_1/kriseev_m_min_of_vector_elements/CMakeLists.txt
- tasks/task_1/kriseev_m_min_of_vector_elements/main.cpp
- tasks/task_1/kriseev_m_min_of_vector_elements/min_of_vector_elements.cpp
- tasks/task_1/kriseev_m_min_of_vector_elements/min_of_vector_elements.h
Нахождение минимального значения элементов матрицы. Для решения матрицу представляем в виде линейной последовательности/вектора и ищем минимум в ней.
Параллельный алгоритм распределяет вектор между всеми процессами при помощи scatter_v, каждый процесс находит локальный минимум в своей подпоследовательности, после чего на главном (0) процессе при помощи reduce находится минимум из локальных минимумов
> Крисеев Михаил. Задача 1. Вариант 14. Минимальное значение элементов матрицы.

- tasks/task_1/Kozyreva_K_word_count/CMakeLists.txt
- tasks/task_1/Kozyreva_K_word_count/main.cpp
- tasks/task_1/Kozyreva_K_word_count/words_count.cpp
- tasks/task_1/Kozyreva_K_word_count/words_count.h
Программа подсчитывает кол-во слов в строке, разделяя строку на несколько частей
> Козырева Екатерина. Задача 1. Вариант 24. Подсчет числа слов в строке

- tasks/task_1/akopyan_z_symbols_count/CMakeLists.txt
- tasks/task_1/akopyan_z_symbols_count/main.cpp
- tasks/task_1/akopyan_z_symbols_count/symbols_count.cpp
- tasks/task_1/akopyan_z_symbols_count/symbols_count.h
Написал программу, которая считает количество буквенных символов в строке. Буквенными символами считаются все символы латинского алфавита независимо от регистра.
Предварительно строка разбивается на несколько частей и распределяется между процессами.
> Акопян Зал. Задача 1. Вариант 22. Подсчёт буквенных символов в строке.

- tasks/task_1/khramov_i_vector_dot_product/CMakeLists.txt
- tasks/task_1/khramov_i_vector_dot_product/main.cpp
- tasks/task_1/khramov_i_vector_dot_product/vector_dot_product.cpp
- tasks/task_1/khramov_i_vector_dot_product/vector_dot_product.h
Суть задачи заключается в нахождении скалярного произведения векторов. Для решения данной задачи каждому процессу выделяется определённое количество элементов обеих векторов (Если количество элементов в обеих векторах не может быть поровну распределено между всеми процессами, оставшиеся элементы направляются нулевому процессу), и из них формируются локальные векторы на каждом процессе. Затем на каждом процессе производится расчёт скалярного произведения локальных векторов при помощи std::inner_product из библиотеки numeric. По завершении все локальные скалярные произведения векторов суммируются на корневом процессе, образуя искомое скалярное произведение. Кроме того, проверяется возможность расчёта скалярного произведения (требуются равные длины обеих векторов).
> Храмов Иван. Задача 1. Вариант 9. Скалярное произведение векторов.

- tasks/task_1/khramov_i_vector_dot_product/CMakeLists.txt
- tasks/task_1/khramov_i_vector_dot_product/main.cpp
- tasks/task_1/khramov_i_vector_dot_product/vector_dot_product.cpp
- tasks/task_1/khramov_i_vector_dot_product/vector_dot_product.h
- tasks/task_2/khramov_i_star_topology/CMakeLists.txt
- tasks/task_2/khramov_i_star_topology/main.cpp
- tasks/task_2/khramov_i_star_topology/star_topology.cpp
- tasks/task_2/khramov_i_star_topology/star_topology.h
- tasks/task_3/khramov_i_global_search/CMakeLists.txt
- tasks/task_3/khramov_i_global_search/global_search.cpp
- tasks/task_3/khramov_i_global_search/global_search.h
- tasks/task_3/khramov_i_global_search/main.cpp
Данная задача является задачей поиска глобального минимума.  Алгоритм глобального поиска позволяет находить абсолютный минимум функции на сетке и основан на вероятностном подходе. На основе набора известных значений функции в точках сетки ищется интервал между соседними точками, на котором абсолютный минимум
наиболее вероятен. На этом интервале берется точка, соответствующая математическому ожиданию положения минимума, вычисляется значение функции в ней. Точка добавляется в список известных значений, и происходит переход к следующей итерации. Алгоритм останавливается, когда расстояние между точками отрезка последовательных итераций становится меньше заданного значения эпсилон.
В данной задаче для рассылки данных, содержащих соседние точки, между процессами используются MPI_Send, MPI_Recv …
> Храмов Иван. Задача 3. Вариант 13. Многошаговая схема решения двумерных задач глобальной оптимизации.  Распараллеливание по характеристикам.

- tasks/task_1/khramov_i_vector_dot_product/CMakeLists.txt
- tasks/task_1/khramov_i_vector_dot_product/main.cpp
- tasks/task_1/khramov_i_vector_dot_product/vector_dot_product.cpp
- tasks/task_1/khramov_i_vector_dot_product/vector_dot_product.h
- tasks/task_2/khramov_i_star_topology/CMakeLists.txt
- tasks/task_2/khramov_i_star_topology/main.cpp
- tasks/task_2/khramov_i_star_topology/star_topology.cpp
- tasks/task_2/khramov_i_star_topology/star_topology.h
В сети с топологией типа "Звезда" каждый процессор связан лишь с главным мастер-процессором. Для решения данной задачи используются функции MPI_Send и MPI_Recv. Алгоритм передачи заключается в том, что для передачи данных  подчинённому-получателю подчинённый-отправитель пересылает данные на мастер-процессор, после чего, он отправляет их подчинённому-получателю. 
Пример: 
мастер-процессор = 0
отправитель = 1
получатель = 3
Схема:
1 -> 0 - отправляем на мастер-процессор
0 <- 1 - получаем на мастере
0 -> 3 - отправляем получателю
3 <- 0 - получаем на получателе
> Храмов Иван. Задача 2. Вариант 12. Топология сети передачи данных "Звезда".

- tasks/task_2/yurin_a_readers_writers/CMakeLists.txt
- tasks/task_2/yurin_a_readers_writers/main.cpp
- tasks/task_2/yurin_a_readers_writers/readers_writers.cpp
- tasks/task_2/yurin_a_readers_writers/readers_writers.h
Существует три типа процессов:
1. Контролёр - всегда процесс с рангом 0
2. Читатели - процессы начиная с 1-го до readerCount
3. Писатели - процессы начиная с (readerCount + 1) до writerCount
Читатели и писатели сообщают, когда готовы начать выполнение (отправляют сообщение с тегом READER_READY_TAG и WRITER_READY_TAG). Дальше ждут ответа от "контролёра" с тегом READER_START_TAG и WRITER_START_TAG. И в конце выполнения отправляют сообщение с тегом READER_END_TAG и WRITER_END_TAG.
Контролер работает до тех пор, пока все процессы (читатели и писатели) не будут завершены. Если в буфере сообщений есть сообщение от писателя, то контролёр принимает его, иначе принимает любое сообщение из буфера. 
Если принято сообщение от читателя, то во время работы этого читателя могут начинать выполнение и …
> Юрин Андрей. Задача 2. Вариант 2. Задача «Читатели-Писатели»

- tasks/task_3/yurin_a_shell_sort_simple_merge/CMakeLists.txt
- tasks/task_3/yurin_a_shell_sort_simple_merge/main.cpp
- tasks/task_3/yurin_a_shell_sort_simple_merge/shell_sort_simple_merge.cpp
- tasks/task_3/yurin_a_shell_sort_simple_merge/shell_sort_simple_merge.h
Массив делится на n приблизительно равных частей. Каждая часть сортируется в отдельном процессе сортировкой Шелла. Дальше отсортированные части собираются одним из двух способов:
1) Части массива собираются в одном процессе и этот процесс их сортирует
2) Части массива собираются в виде дерева (работает ~в 1.5 раза быстрей, чем первый способ)
> Юрин Андрей. Задача 3. Вариант 16. Сортировка Шелла простым слиянием

- tasks/task_2/zawadowski_j_broadcast/CMakeLists.txt
- tasks/task_2/zawadowski_j_broadcast/broadcast.cpp
- tasks/task_2/zawadowski_j_broadcast/broadcast.h
- tasks/task_2/zawadowski_j_broadcast/main.cpp
Данная программа выполняет передачу данных от одного процесса ко всем другим (broadcast). Метод был реализован с использованием таких функций как MPI_Send и MPI_Recv. Также были проведены тесты для сравнения скорости выполнения встроенной функции (MPI_Bcast) и той, что написана мною. Функция MPI_Bcast осуществляет рассылку данных из буфера, содержащего определенное количество элементов заданного типа с процесса, имеющего указанный номер, всем процессам, входящим в определенный коммуникатор.
Результаты тестов показали, что встроенная функция MPI_Bcast выполняется быстрее, чем функция broadcast, которая была написана мною.
> Завадовский Ян. Задача 2. Вариант 5. Передача от одного всем (broadcast).

- tasks/task_1/travin_m_max_of_vector_elements/CMakeLists.txt
- tasks/task_1/travin_m_max_of_vector_elements/main.cpp
- tasks/task_1/travin_m_max_of_vector_elements/max_of_vector_elements.cpp
- tasks/task_1/travin_m_max_of_vector_elements/max_of_vector_elements.h
Необходимо найти минимальное значение в векторе. Для этого процессам выделяется несколько элементов вектора, и каждый процесс находит минимум среди переданных ему элементов. Затем среди найденных элементов выбирается наименьший, который будет минимальным в исходном векторе.
> Травин Максим. Задача 1. Вариант 3. Максимальное значение элементов вектора

- tasks/task_2/travin_m_yakoby_method/CMakeLists.txt
- tasks/task_2/travin_m_yakoby_method/main.cpp
- tasks/task_2/travin_m_yakoby_method/yakoby_method.cpp
- tasks/task_2/travin_m_yakoby_method/yakoby_method.h
Итерационный метод Якоби - это численный метод решения систем линейных уравнений. Он используется для приближенного нахождения решения системы Ax = b, основываясь на итеративном процессе.
В контексте метода Якоби векторы "x" и "new_x" представляют собой приближенные решения системы линейных уравнений на различных этапах итерационного процесса.
Обмен данных между процессами происходит с использованием вектора "new_x" внутри функции MPI_Allgatherv, после чего возвращается результирующий вектор "x".
> Травин Максим. Задача 2. Вариант 22. Итеративные методы(Якоби)

- tasks/task_3/travin_m_global_opt/CMakeLists.txt
- tasks/task_3/travin_m_global_opt/global_opt.cpp
- tasks/task_3/travin_m_global_opt/global_opt.h
- tasks/task_3/travin_m_global_opt/main.cpp
Код реализует метод глобальной оптимизации с использованием параллельных вычислений с помощью библиотеки MPI.
Функции getparametrL, getparametrM, getparametr_m находят вычисляют соответствующие параметры M, m, L, которые используются для расчета характеристики интервала. В дальнейшем на процессы отправляется информация о каждом, затем результаты собираются в процессе с рангом 0.
>  Травин Максим. Задача 3. Вариант 13. Многошаговая схема решения двумерных задач глобальной оптимизации. Распараллеливание по характеристикам.

- tasks/task_1/durandin_v_max_of_vector_elements/CMakeLists.txt
- tasks/task_1/durandin_v_max_of_vector_elements/main.cpp
- tasks/task_1/durandin_v_max_of_vector_elements/vector_max_element.cpp
- tasks/task_1/durandin_v_max_of_vector_elements/vector_max_element.h
Задача: реализовать нахождение максимального элемента вектора с помощью MPI. В данной работе использовались коллективные функции MPI_Scatterv для распределения частей вектора по процессам, и MPI_Reduce для получения глобального максимального значения из локальных максимумов с каждого процесса.
> Дурандин Владимир. Задача 1. Вариант 3. Максимальное значение элементов вектора.

- tasks/task_1/sredneva_a_sum_values_of_matrix_columns/CMakeLists.txt
- tasks/task_1/sredneva_a_sum_values_of_matrix_columns/main.cpp
- tasks/task_1/sredneva_a_sum_values_of_matrix_columns/sum_values.cpp
- tasks/task_1/sredneva_a_sum_values_of_matrix_columns/sum_values.h
Задача заключается в нахождении суммы значений по столбцам матрицы. Была реализована последовательная и параллельная версия алгоритма. В параллельной версии функция MPI_Scatterv позволяет распределить столбцы исходной матрицы по процессам, а MPI_Gatherv - получить суммы по столбцам со всех процессов и собрать их в один вектор.
> Среднева Анастасия. Задача 1. Вариант 12. Сумма значений по столбцам матрицы.

- tasks/task_1/kulagin_a_find_matrix_col_min/CMakeLists.txt
- tasks/task_1/kulagin_a_find_matrix_col_min/find_matrix_col_min.cpp
- tasks/task_1/kulagin_a_find_matrix_col_min/find_matrix_col_min.h
- tasks/task_1/kulagin_a_find_matrix_col_min/main.cpp
Функции: `find_matrix_col_min_sequential` и `find_matrix_col_min_parallel` для последовательного вычисления и параллельного соответственно. Обе функции шаблонные (тип `T`), принимают указатель на массив `T*`: матрицу в векторном формате, количество строк (`int`), количество столбцов (`int`) и `MPI_Datatype`, который соответствует `T` (в последовательной он ничего не делает). Обе функции возвращают указатель на массив размера `cols`, который содержит минимальные значения по столбцам матрицы. Этот массив потом нужно будет освобождать. `root = 0`.
В параллельной реализации каждый процесс берёт на себя `delta = cols / proc_num` столбцов для подсчёта минимума для `delta` столбцов. Так же `root` процесс берёт на себя `delta + delta_left`, где `delta_left = cols % proc_num` (т.е. остаток, если …
> Кулагин Александр. Задача 1. Вариант 18. Нахождение минимальных значений по столбцам матрицы.

- tasks/task_2/nogin_d_scatter/CMakeLists.txt
- tasks/task_2/nogin_d_scatter/algo.cpp
- tasks/task_2/nogin_d_scatter/algo.h
- tasks/task_2/nogin_d_scatter/main.cpp
Необходимо написать функцию обобщённой передачи данных от одного всем (scatter). В функции используются только MPI_Send и MPI_Recv. Функция имеет тот же прототип, что и соответствующая функция MPI_Scatter. 
Тестовая программа позволяет выбрать номер процесса root и выполнять рассылку массива следующих типов: MPI_INT, MPI_FLOAT, MPI_DOUBLE.
> Ногин Денис. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter).

- tasks/task_1/shishkina_v_lexicographic_strings/CMakeLists.txt
- tasks/task_1/shishkina_v_lexicographic_strings/lexicographic_strings.cpp
- tasks/task_1/shishkina_v_lexicographic_strings/lexicographic_strings.h
- tasks/task_1/shishkina_v_lexicographic_strings/main.cpp
Данная задача заключается в проверке на лексикографическую упорядоченность двух строк. Реализована последовательная и параллельная версия алгоритма. В последовательной версии на вход поступали две строки (char*), с помощью функции strcmp() строки сравнивались. В случае, если первая строка была меньше либо равна второй, возвращалась 1, что свидетельствовало о том, что строки упорядочены, в противном случае - 0, строки не упорядочены. Для реализации параллельного алгоритма использовалась функция MPI_Scatterv(), которая позволяет распределить данные от выбранного процесса всем остальным, поскольку размер порции может быть разным, использовала именно эту функцию, а не MPI_Scatter(). Также для объединения результат использовалась функция MPI_Reduce().
> Шишкина Валерия. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.

- tasks/task_3/shishkina_l_metodSimpsona/CMakeLists.txt
- tasks/task_3/shishkina_l_metodSimpsona/main.cpp
- tasks/task_3/shishkina_l_metodSimpsona/metodSimpsona.cpp
- tasks/task_3/shishkina_l_metodSimpsona/metodSimpsona.h
Данная задача заключается в вычислении двумерного интеграла методом Симпсона. Была реализована последовательная и параллельная версия. Основная идея реализации заключается в том, чтобы разбить область интегрирования на части и распределить их между процессами. Затем результаты суммируются для получения окончательного результата. Использовалась функция MPI_Reduce для суммирования локальных сумм интеграла каждого процесса и получение глобальной суммы на процессе с рангом 0. Результат глобальной суммы используется для вычисления окончательного значения интеграла.
> Шишкина Валерия. Задача 3. Вариант 9.  Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

- tasks/task_1/ionova_e_int_rect/CMakeLists.txt
- tasks/task_1/ionova_e_int_rect/int_rect.cpp
- tasks/task_1/ionova_e_int_rect/int_rect.h
- tasks/task_1/ionova_e_int_rect/main.cpp
Предел интегрирования `(a, b)` разбивается равномерно между процессами. Далее каждый процесс считает интеграл по своему пределу `localA` и `localB`.
> Ионова Екатерина. Задача 1. Вариант 19. Интегрирование – метод прямоугольников.

- tasks/task_3/ionova_e_gauss_block/CMakeLists.txt
- tasks/task_3/ionova_e_gauss_block/gauss_block.cpp
- tasks/task_3/ionova_e_gauss_block/gauss_block.h
- tasks/task_3/ionova_e_gauss_block/main.cpp
`Фильтр Гаусса` - это тип фильтра, который применяется в обработке изображений для сглаживания изображения и уменьшения шума. Он основан на математической функции Гаусса, которая создает распределение значений вокруг центральной точки.
Применение фильтра Гаусса осуществляется путем применения ядра Гаусса к каждому пикселю изображения. Ядро Гаусса представляет собой двумерную матрицу значений, которая сглаживает окружающие пиксели на основе гауссовского распределения весов.
> Ионова Екатерина. Задача 3. Вариант 28. Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3.

- tasks/task_1/kashin_s_nearest_neighbor_elements/CMakeLists.txt
- tasks/task_1/kashin_s_nearest_neighbor_elements/main.cpp
- tasks/task_1/kashin_s_nearest_neighbor_elements/neighbor_elements.cpp
- tasks/task_1/kashin_s_nearest_neighbor_elements/neighbor_elements.h
Делим отрезок на n отрезков(n количество процессов), где последний элемент отрезка является началом следующего отрезка. Вычисляем наименьшую разницу между соседними элементами и возвращаем pair<разница, индекс левого соседа> с помощью MPI_Reduce сравниваем пары(MPI_2INT) и ищем минимальную, ответом будут минимальная разница и индекс первого соседа с такой минимальной разницей.
> Кашин Степан. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.

- tasks/task_2/kashin_s_gauss_method_horizontal/CMakeLists.txt
- tasks/task_2/kashin_s_gauss_method_horizontal/gauss_method_horizontal.cpp
- tasks/task_2/kashin_s_gauss_method_horizontal/gauss_method_horizontal.h
- tasks/task_2/kashin_s_gauss_method_horizontal/main.cpp
Основной поток делегирует работы по вычитанию строк процессам через MPI_Scatterv, кроме этого основной процесс передает размеры строк и строку которую надо будет вычитать через MPI_Bcast. По завершении процессов своей работы данные над которыми работали процессы, собираются в 0вом процессе с помощью MPI_Gatherv. После завершения прямого хода Гаусса, нулевой процесс выполняет обратный.
> Кашин Степан. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.

- tasks/task_1/veselov_i_min_values_for_matrix_columns/CMakeLists.txt
- tasks/task_1/veselov_i_min_values_for_matrix_columns/main.cpp
- tasks/task_1/veselov_i_min_values_for_matrix_columns/minValForMatrix.cpp
- tasks/task_1/veselov_i_min_values_for_matrix_columns/minValForMatrix.h
Веселов Илья. Задача 1. Вариант 18. Нахождение минимальных значений по столбцам матрицы.
> Веселов Илья. Задача 1. Вариант 18. Нахождение минимальных значений по столбцам матрицы.

- tasks/task_3/kosarev_e_quick_sort_merge/CMakeLists.txt
- tasks/task_3/kosarev_e_quick_sort_merge/main.cpp
- tasks/task_3/kosarev_e_quick_sort_merge/quick_sort_merge.cpp
- tasks/task_3/kosarev_e_quick_sort_merge/quick_sort_merge.h
Представлена реализация быстрой сортировки с простым слиянием.
Функция `split` разделяет массив на две части относительно опорного элемента и возвращает пару индексов, указывающих на конец левой части и начало правой части.
`recursive_quick_sort` - это рекурсивная функция быстрой сортировки. Она использует `split` для разделения массива и затем вызывает себя рекурсивно для обеих полученных частей.
`Merge` объединяет два отсортированных массива в один, используя дополнительную память для временного массива.
`parallelQuickSort` -  быстрая сортировка с использованием MPI для распределения данных и сбора результатов от различных процессов.
`checking` проверяет, отсортирован ли массив, возвращая true, если он отсортирован, иначе - false.
> Косарев Егор. Задача 3. Вариант 14.  Быстрая сортировка с простым слиянием.

- tasks/task_1/kostin_a_average_of_vector_elements/CMakeLists.txt
- tasks/task_1/kostin_a_average_of_vector_elements/average_of_vector_elements.cpp
- tasks/task_1/kostin_a_average_of_vector_elements/average_of_vector_elements.h
- tasks/task_1/kostin_a_average_of_vector_elements/main.cpp
Нахождение среднего арифметического. getRandomVector генерирует рандомный вектор, getParallelAverage находит в векторе среднее арифметическое с использованием MPI. В тестах сравнил полученное значение значение с эталонным.
> Костин Артём. Задача 1. Вариант 2. Вычисление среднего значения элементов вектора.

- tasks/task_2/kostin_a_circle_topology/CMakeLists.txt
- tasks/task_2/kostin_a_circle_topology/circle_topology.cpp
- tasks/task_2/kostin_a_circle_topology/circle_topology.h
- tasks/task_2/kostin_a_circle_topology/main.cpp
Топология “кольцо” - это тип сетевой архитектуры, в которой узлы соединены последовательно, образуя кольцо. Данные перемещаются по кольцу в одном направлении, переходя от одного узла к следующему, пока не достигнут конечной точки. Когда конечная точка получает данные, она перенаправляет их обратно на начало кольца, так что данные в конечном итоге проходят через все узлы.
> Костин Артём. Задача 2. Вариант 11. Топология сети передачи данных кольцо.

- tasks/task_1/moiseev_n_num_of_alternations_signs/CMakeLists.txt
- tasks/task_1/moiseev_n_num_of_alternations_signs/main.cpp
- tasks/task_1/moiseev_n_num_of_alternations_signs/num_of_alternations_signs.cpp
- tasks/task_1/moiseev_n_num_of_alternations_signs/num_of_alternations_signs.h
Задача :  реализовать нахождение числа чередований знаков значений соседних элементов вектора. Для решения задачи использую MPI_Scatterv для распределения памяти вектора поровну между процессами . Затем с помощью MPI_Allreduce суммируем результат.
> Моисеев Никита. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора.

- tasks/task_2/chuvashov_a_ring_topology/CMakeLists.txt
- tasks/task_2/chuvashov_a_ring_topology/main.cpp
- tasks/task_2/chuvashov_a_ring_topology/ring_topology.cpp
- tasks/task_2/chuvashov_a_ring_topology/ring_topology.h
Топология сетей передачи данных "Кольцо" - это топология локальной сети, в которой рабочие станции или компьютеры подключены последовательно друг к другу, образуя замкнутое кольцо. В данной программе реализован алгоритм кольцевой топологии с использованием MPI. Определяется исходный процесс (source) и конечный процесс (receiver). В программе присутствуют необходимые условия из определения топологии "Кольцо" - каждый узел сети имеет имеет ровно две исходящие связи, следовательно в топологии не может быть менее двух узлов (т.е. двух процессов). Программа пересылает между узлами целочисленное значение и проверяет его на корректность после получения.
> Чувашов Андрей. Задача 2. Вариант 11. Топология сетей передачи данных "Кольцо".

- tasks/task_1/sokolova_d_counting_the_number_of_sentences_in_string/CMakeLists.txt
- tasks/task_1/sokolova_d_counting_the_number_of_sentences_in_string/counting_the_number_of_sentences_in_string.cpp
- tasks/task_1/sokolova_d_counting_the_number_of_sentences_in_string/counting_the_number_of_sentences_in_string.h
- tasks/task_1/sokolova_d_counting_the_number_of_sentences_in_string/main.cpp
С помощью MPI я распределяю строки между процессами, вычисляю количество предложений в каждой части и затем суммирую результаты для получения общего числа предложений.
> Соколова Дарья. Задача 1. Вариант 25. Подсчет числа предложений в строке

- tasks/task_2/sokolova_d_scatter/CMakeLists.txt
- tasks/task_2/sokolova_d_scatter/main.cpp
- tasks/task_2/sokolova_d_scatter/scatter.cpp
- tasks/task_2/sokolova_d_scatter/scatter.h
Реализована функция передачи от одного ко всем (scatter). Функция scatter использует MPI_Send и MPI_Recv для передачи данных между процессами. Если процесс является корневым (root), то он отправляет данные всем другим процессам, используя MPI_Send. Процесс с номером root копирует данные в буфер приема recv_data, в то время как остальные процессы принимают данные с помощью MPI_Recv. Функция имеет тот же прототип, что и соответствующая функция MPI_Scatter.
> Соколова Дарья. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter).

- tasks/task_2/vanushkin_d_seidel_method/CMakeLists.txt
- tasks/task_2/vanushkin_d_seidel_method/main.cpp
- tasks/task_2/vanushkin_d_seidel_method/seidel_method.cpp
- tasks/task_2/vanushkin_d_seidel_method/seidel_method.h
Требуется решить СЛАУ используя итеративный метод Зейделя.
Метод Зейделя вычисляет столбец решений приближённо, с заданной точностью ответа.
- В параллельной реализации число уравнений распределяется поровну между процессами,
остаток раздаётся процессам в порядке от первого.
- Процессы, решившие свои уравнения, обмениваются данными между собой, для обеспечения наличия актуального
решения на всех процессах.
- Обмен производится до тех пор, пока "норма" между предыдущим и следующим решением будет больше
заданной точности.
> Ванюшкин Дмитрий. Задача 2. Вариант 23. Итеративные методы (Зейделя).

- tasks/task_1/kurdina_j_sum_of_vector_elements/CMakeLists.txt
- tasks/task_1/kurdina_j_sum_of_vector_elements/main.cpp
- tasks/task_1/kurdina_j_sum_of_vector_elements/sum_elements.cpp
- tasks/task_1/kurdina_j_sum_of_vector_elements/sum_elements.h
Целью задачи является нахождение суммы элементов матрицы. Для решения задачи было реализовано несколько функций:  последовательная и параллельная версия, возвращающая сумму, и создание случайной матрицы для тестирования. Для написания параллельной программы была использована функция MPI_Scatterv, которая позволяет распределить элементы исходной матрицы по процессам, причем количество элементов в процессах может быть разным. Затем в каждом процессе подсчитываются локальные суммы, которые будут собраны в нулевом процессе с помощью MPI_Reduce.
> Курдина Юлия. Задача 1. Вариант 10. Сумма элементов матрицы.

- tasks/task_2/kurdina_j_column_wise/CMakeLists.txt
- tasks/task_2/kurdina_j_column_wise/column_wise.cpp
- tasks/task_2/kurdina_j_column_wise/column_wise.h
- tasks/task_2/kurdina_j_column_wise/main.cpp
Задача заключается в умножении матрицы на вектор с помощью ленточного разбиения столбцов матрицы. Суть данного разбиения заключается в умножении каждого элемента столбца матрицы на один из элементов вектора. Для решения задачи были реализованы последовательная и параллельная версия алгоритма, а также вспомогательные функции: транспонирование матрицы и создание случайной матрицы для тестирования. Функция MPI_Scatterv была использована дважды: для распределения столбцов матрицы по процессам, причем в одном процессе может быть несколько столбцов, и для распределения соответствующих элементов вектора по процессам. Затем в каждом процессе получаем вектор промежуточных результатов. Функция MPI_Reduce произведет сложение этих векторов в результирующий.
> Курдина Юлия. Задача 2. Вариант 16. Ленточная вертикальная схема.

- tasks/task_2/saratova_m_ribbon_horizontal_scheme/CMakeLists.txt
- tasks/task_2/saratova_m_ribbon_horizontal_scheme/main.cpp
- tasks/task_2/saratova_m_ribbon_horizontal_scheme/ribbon_horizontal_scheme.cpp
- tasks/task_2/saratova_m_ribbon_horizontal_scheme/ribbon_horizontal_scheme.h
В данной задаче мною был реализован последовательный алгоритм умножения матриц, а также параллельный алгоритм умножения матриц с использованием ленточной горизонтальной схемы. Суть задачи заключается в том, чтобы равномерно распределить строки первой матрицы между процессами, на каждом процессе умножить полученный "кусок" на вторую матрицу, собрать результаты с каждого процесса и сделать из этого итоговый результат. Для передачи частей первой матрицы использовалась функция MPI_Scatterv, а для передачи второй матрицы всем процессам использовалась функция MPI_Bcast. Для сбора результата с каждого процесса использовалась функция MPI_Gatherv
> Саратова Марина. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А.

- tasks/task_3/saratova_m_quick_sort/CMakeLists.txt
- tasks/task_3/saratova_m_quick_sort/main.cpp
- tasks/task_3/saratova_m_quick_sort/quick_sort.cpp
- tasks/task_3/saratova_m_quick_sort/quick_sort.h
В данной работе мною была реализована параллельная версия быстрой сортировки. Исходный вектор данных разделяется между процессами с помощью функции task_distribution, которая определяет количество элементов для сортировки каждым процессом. Каждый процесс получает свою часть данных, сортирует их локально с использованием std::sort, после чего отсортированные части отправляются обратно процессу с рангом 0 при помощи функций MPI_Send и MPI_Recv. Процесс с рангом 0 последовательно сливает отсортированные части данных в один отсортированный вектор с помощью std::merge.  В итоге получается отсортированный вектор, которая объединяет в себе результаты сортировки каждого процесса. 
Данная программа тестировалась на простом векторе, векторе с отрицательными числами, векторе с большим количеством …
> Саратова Марина. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.

- tasks/task_1/safarov_n_non_matching_symbols/CMakeLists.txt
- tasks/task_1/safarov_n_non_matching_symbols/main.cpp
- tasks/task_1/safarov_n_non_matching_symbols/number_of_different_symbols.cpp
- tasks/task_1/safarov_n_non_matching_symbols/number_of_different_symbols.h
Цель данной лабораторной работы — вычислить количество несовпадающих символов двух строк. В приведённом ниже коде была реализована последовательная (numberOfNonMatchingCharacters_Consistently()) и параллельная (numberOfNonMatchingCharacters_Parallel()) версии алгоритма. Кроме того, здесь присутствует функция generateRandomString(), которая генерирует случайные строки.
В случае, если длины строк отличаются друг от друга, выполняется выравнивание строк по длине, добавляя символ "$" в конец строки с меньшей длиной. Зачем? С целью обеспечить равную длину строк для параллельного выполнения и корректного разделения данных между процессами. Далее происходит распределение данных (символов строк) между всеми процессами (одного коммуникатора) с использованием функции MPI_Scatterv(). Это позволяет …
> Сафаров Нурлан. Задача 1. Вариант 27. Подсчёт числа несовпадающих символов двух строк.

- tasks/task_1/smirnov_p_most_different_neighbor_elements/CMakeLists.txt
- tasks/task_1/smirnov_p_most_different_neighbor_elements/main.cpp
- tasks/task_1/smirnov_p_most_different_neighbor_elements/most_different_vector_elements.cpp
- tasks/task_1/smirnov_p_most_different_neighbor_elements/most_different_vector_elements.h
Требуется найти два соседних элемента вектора, которые имеют наибольшую разницу в значениях. Каждому процессу передается свой локальный вектор, представляющий часть основного вектора. Внутри каждого локального вектора ищется пара соседних элементов, у которых разница в значениях максимальна. Далее из найденных пар выбирается та, у которой разница максимальна.
> Смирнов Павел. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.

- tasks/task_2/smirnov_p_method_of_Seidel/CMakeLists.txt
- tasks/task_2/smirnov_p_method_of_Seidel/main.cpp
- tasks/task_2/smirnov_p_method_of_Seidel/seidel.cpp
- tasks/task_2/smirnov_p_method_of_Seidel/seidel.h
Функция seidel_solve содержит параллельную реализацию метода Зейделя с использованием MPI. Этот метод позволяет решать систему линейных уравнений. В этой реализации происходит разделение области ответственности между процессами с использованием MPI, что позволяет ускорить вычисления для больших систем.
seidel_solve использует распределенные вычисления с помощью MPI для ускорения процесса решения системы линейных уравнений. В то время как seidel_solve_s выполняет вычисления последовательно, без использования параллельных вычислений.
> Смирнов Павел. Задача 2. Вариант 23. Итеративные методы (Зейделя)

- tasks/task_1/smirnova_d_max_matrix_element/CMakeLists.txt
- tasks/task_1/smirnova_d_max_matrix_element/main.cpp
- tasks/task_1/smirnova_d_max_matrix_element/max_matrix_element.cpp
- tasks/task_1/smirnova_d_max_matrix_element/max_matrix_element.h
Нахождение максимального значения элементов матрицы. 
Код содержит функции для генерации случайной матрицы — generate_random_Matrix. Нахождения максимального элемента в матрице представленной в виде вектора — findMaxOfMatrix. И параллельного нахождения максимального элемента в матрице с помощью разделения данных между процессами и последующим объединением результатов — findMaxOfMatrixParallel. 
findMaxOfMatrixParallel — определяет размер и ранг процесса, рассчитывает количество элементов на каждый процесс (elem_per_process) и остаток (remainder), рассылает глобальную матрицу по процессам с помощью MPI_Scatterv и использует MPI_Reduce, чтобы собрать локальные максимумы и найти глобальный максимум.
> Смирнова Дарья. Задача 1. Вариант 13. Максимальное значение элементов матрицы.

- tasks/task_1/podyachikh_m_most_different_elements/CMakeLists.txt
- tasks/task_1/podyachikh_m_most_different_elements/main.cpp
- tasks/task_1/podyachikh_m_most_different_elements/most_different_elements.cpp
- tasks/task_1/podyachikh_m_most_different_elements/most_different_elements.h
Функции `GetMostDifferentElements` возвращают наибольшее значение модуля разности соседних элементов.
`ParallelGetMostDifferentElements` раздает процессам равное количество элементов. Затем остаток распределяется между первыми процессами, каждому по одному элементу добавится.
Чтобы не пропустить пары соседей, находящиеся на границах подмассивов, к каждому подмассиву кроме последнего непустого добавляется один элемент из начала следующего подмассива.
Данные с процессов собираются функцией `MPI_Reduce` операцией `MPI_MAX`.
> Подъячих Михаил. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.

- tasks/task_2/podyachikh_m_reduce/CMakeLists.txt
- tasks/task_2/podyachikh_m_reduce/main.cpp
- tasks/task_2/podyachikh_m_reduce/reduce.cpp
- tasks/task_2/podyachikh_m_reduce/reduce.h
- Отправка:
С любого процесса (кроме `root`) данные отправляются ровно один раз (`root` не отправляет данные).
Данные отправляются на процесс с рангом, который отличается от текущего ранга тем, что самый правый единичный бит исходного ранга заменен на ноль.
```cpp 
int new_rank = (rank - 1) & rank;
```
Например, для ранга, битовое представление которого `11011000`, операция, убирающая последнюю единицу происходит так:
```cpp
11011000 -> ( rank - 1 )
11010111 -> ( & rank )
11010000 
```
- Получение:
Соответственно происходит со всех процессов, ранги которых отличаются от текущего заменой одного нулевого бита на единицу. Заменяемый бит должен находиться до первого бита единицы в исходном ранге.
Например, для ранга, битовое представление которого `11010000`, подходят ранги: `11010001`, …
> Подъячих Михаил. Задача 2. Вариант 6. Передача от всех одному (reduce).

- tasks/task_1/borovkov_s_int_reg/CMakeLists.txt
- tasks/task_1/borovkov_s_int_reg/alg.cpp
- tasks/task_1/borovkov_s_int_reg/alg.h
- tasks/task_1/borovkov_s_int_reg/main.cpp
Данная программа реализует численное интегрирование функции на отрезке [a, b] с использованием метода прямоугольников. Программа содержит две функции: `integrateSequential` и `integrateParallel`. Первая функция выполняет последовательное интегрирование, а вторая - параллельное, используя MPI для распределения работы между процессами.
> Боровков Сергей. Задача 1. Вариант 19. Интегрирование – метод прямоугольников.

- tasks/task_3/borovkov_s_gauss_vert/CMakeLists.txt
- tasks/task_3/borovkov_s_gauss_vert/alg_gauss_vert.cpp
- tasks/task_3/borovkov_s_gauss_vert/alg_gauss_vert.h
- tasks/task_3/borovkov_s_gauss_vert/main.cpp
Этот код содержит реализацию последовательного и параллельного алгоритма фильтрации изображения с использованием ядра Гаусса. Функция `getParallelGauss` выполняет параллельную фильтрацию изображения с использованием ядра Гаусса с использованием MPI. Она разбивает изображение на равные части и распределяет их между процессами. Каждый процесс выполняет последовательную фильтрацию своей части изображения, а затем результаты собираются в глобальный массив. Если количество процессов больше, чем ширина изображения, то используется последовательный алгоритм.
> Боровков Сергей. Задача 3. Вариант 27. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.

- tasks/task_2/mironov_i_prod_cons/CMakeLists.txt
- tasks/task_2/mironov_i_prod_cons/main.cpp
- tasks/task_2/mironov_i_prod_cons/prod_cons.cpp
- tasks/task_2/mironov_i_prod_cons/prod_cons.h
На 0 процессе расположен циклический буфер. Производители пытаются туда положить данные, потребители - забрать. Необходимо обеспечить их параллельную работу, чтобы производители не могли положить в уже полный буфер, а потребители - забрать из пустого
> Миронов Илья. Задача 2. Вариант 1. Задача «Производители-потребители».

- tasks/task_1/kasimtcev_min_of_vector_elements/CMakeLists.txt
- tasks/task_1/kasimtcev_min_of_vector_elements/main.cpp
- tasks/task_1/kasimtcev_min_of_vector_elements/matrix_min.cpp
- tasks/task_1/kasimtcev_min_of_vector_elements/matrix_min.h
Задача состоит в нахождении минимального значения во всей матрице.
Функция `FndMin` ищет минимум в заданной матрице, функция `FndMinParallel` является параллельным аналогом функции `FndMin`.
Алгоритм функции `FndMinParallel` таков: принимается матрица, строки которой выстроены одна за другой. Определяется количество последовательных элементов "развернутой" матрицы, которые будут выделены каждому процессу, далее происходит отправка полученных частей матрицы, для каждой из которых находится локальный минимум. Затем главный процесс получает локальные минимумы от процессов-потомков и определяет среди них глобальный. Глобальный минимум возвращается как результат функции.
> Касимцев Роман. Задача 1. Вариант 14. Минимальное значение элементов матрицы.

- tasks/task_2/kasimtcev_reduce/CMakeLists.txt
- tasks/task_2/kasimtcev_reduce/main.cpp
- tasks/task_2/kasimtcev_reduce/reduce.cpp
- tasks/task_2/kasimtcev_reduce/reduce.h
Передача от всех одному (reduce)
Дерево процессов представлено бинарным деревом, а именно: из самого нижнего уровня данные переходят в корень дерева. При прохождении ребра с данными происходит редукция. Данные переходят по всем путям, кроме пути от корня дерева до root. Когда данные дойдут до корня дерева, они отправляются до root. Таким образом, на root придёт результат.
> Касимцев Роман. Задача 2. Вариант 6. Передача от всех одному (reduce).

- tasks/task_1/vetoshnikova_k_vector_dot_product/CMakeLists.txt
- tasks/task_1/vetoshnikova_k_vector_dot_product/main.cpp
- tasks/task_1/vetoshnikova_k_vector_dot_product/vector_dot_product.cpp
- tasks/task_1/vetoshnikova_k_vector_dot_product/vector_dot_product.h
Необходимо вычислить скалярное произведения двух векторов. Реализованы параллельная и последовательная версии решения поставленной задачи. В первом варианте оба вектора разбиваются на блоки разного размера, которые затем передаются процессам. Использовалась функция MPI_Scatterv(). В каждом процессе вычисляются частичные скалярные произведения. После этого вычисленные значения редуцируются в нулевом процессе с помощью функции MPI_Reduce().
> Ветошникова Екатерина. Задача 1. Вариант 9. Скалярное произведение векторов.

- tasks/task_1/kudinov_n_lexicographic_strings/CMakeLists.txt
- tasks/task_1/kudinov_n_lexicographic_strings/lexicographic_strings.cpp
- tasks/task_1/kudinov_n_lexicographic_strings/lexicographic_strings.h
- tasks/task_1/kudinov_n_lexicographic_strings/main.cpp
Разбиваем две строки на `n` равных частей, где `n` соответствует количеству процессов. Распределяем эти части между процессами с помощью операции `boost::mpi::scatter`. Каждый процесс проверяет на упорядоченность выделенные для него подстроки. Затем собираем полученные результаты с помощью операции `boost::mpi::reduce` с функцией `std::logical_and`
> Кудинов Никита. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.

- tasks/task_2/kudinov_n_matrix_multiplication_vertical/CMakeLists.txt
- tasks/task_2/kudinov_n_matrix_multiplication_vertical/main.cpp
- tasks/task_2/kudinov_n_matrix_multiplication_vertical/matrix_multiplication_vertical.cpp
- tasks/task_2/kudinov_n_matrix_multiplication_vertical/matrix_multiplication_vertical.h
> Кудинов Никита. Задача 2. Вариант 16. Ленточная вертикальная схема.

- tasks/task_1/smirnov_l_matrix_col_sum/CMakeLists.txt
- tasks/task_1/smirnov_l_matrix_col_sum/main.cpp
- tasks/task_1/smirnov_l_matrix_col_sum/matrix_col_sum.cpp
- tasks/task_1/smirnov_l_matrix_col_sum/matrix_col_sum.h
Задача состоит в том, чтобы посчитать суммы элементов по столбцам матрицы:
1) Матрица представляется в виде обычного вектора;
2) Происходит транспонирование матрицы, после чего задача уже сводиться к суммированию элементов строк, а сделано это для того, чтобы удобнее было отправлять данные в виде непрерывной области памяти.
3) Параллельная работа заключается в следующем:
3.1) Определяется распределение элементов матрицы между процессами: сколько кому отдать и какое при этом будет смещение.
3.2) Корневой процесс, через Scatterv распределяет данный между процессами, каждый из которых с помощью последовательной реализации, считает суммы отведенных ему строк с элементами.
3.3) После этого, через Gatherv корневой процесс соединяет кусочки результатов после подсчетов каждым процессов в одно …
> Смирнов Леонид. Задача 1. Вариант 12. Сумма значений по столбцам матрицы.

- tasks/task_1/mortina_a_average_of_vector_elements/CMakeLists.txt
- tasks/task_1/mortina_a_average_of_vector_elements/alg.cpp
- tasks/task_1/mortina_a_average_of_vector_elements/alg.h
- tasks/task_1/mortina_a_average_of_vector_elements/main.cpp
Была разработана программа, вычисляющее среднее значение элементов вектора. 
Функция `sumOfVectorSequential` вычисляет сумму всех элементов вектора `vector` последовательно, используя цикл `for`.
Функция `midValueOfVectorParallel` вычисляет среднее значение элементов вектора `vector` параллельно с использованием библиотеки Boost.MPI. 
Каждый процесс получает свою часть вектора, вычисляет сумму своих элементов с помощью функции `sumOfVectorSequential`, а затем использует функцию `boost::mpi::reduce` для суммирования всех локальных сумм и получения общей суммы. Наконец, среднее значение вычисляется путем деления глобальной суммы на размер вектора.
> Мортина Анастасия. Задача 1. Вариант 2. Вычисление среднего значения элементов вектора.

- tasks/task_3/mortina_a_mult_monte_carlo/CMakeLists.txt
- tasks/task_3/mortina_a_mult_monte_carlo/main.cpp
- tasks/task_3/mortina_a_mult_monte_carlo/monte_carlo.h
Эта программа реализует метод Монте-Карло для вычисления многократных интегралов в заданной области в пространстве заданной размерности. 
Она включает две функции: `multiple_integral_monte_carlo_parallel` и `multiple_integral_monte_carlo_sequential`. Первая функция реализует параллельный алгоритм, используя MPI для распределения вычислительной нагрузки между процессами. 
Вторая функция реализует последовательный алгоритм. Обе функции принимают функцию, которую нужно интегрировать, функцию, которая определяет, находится ли точка в заданной области, массив границ интегрирования и число итераций. Результатом работы функций является численное значение интеграла.
> Мортина Анастасия. Задача 3. Вариант 10. Вычисление многомерных интегралов методом Монте-Карло.

- CMakeLists.txt
- tasks/task_1/korablev_int_mont/CMakeLists.txt
- tasks/task_1/korablev_int_mont/integral.cpp
- tasks/task_1/korablev_int_mont/integral.h
- tasks/task_1/korablev_int_mont/main.cpp
Область интегрирования разделяется равномерно между процессами и внутри каждого процесса вычисляется интеграл по локальной области по методу Моте-Карло.
> Кораблев Никита. Задача 1. Вариант 21. Интегрирование – метод Монте-Карло.

- tasks/task_2/korablev_zeidel/CMakeLists.txt
- tasks/task_2/korablev_zeidel/main.cpp
- tasks/task_2/korablev_zeidel/zeidel.cpp
- tasks/task_2/korablev_zeidel/zeidel.h
В программе реализован Зейделя для решения СЛАУ, а так же его распаралеленная версия. На вход методы имеют три параметра: матрица, представленная в виде вектора и хранящая в конце вектор b, размерность данной матрицы и необходимая точность. Так же, для матрицы, которая подойтся на вход, выполняется диагональное преобладание. 
Кждая строка матрицы "A" распределяется между процессами. И так как, строка i зависит от всех предыдущих строк, за раз мы можем посчитать только x_i, после чего мы сможем передать полученное значение всем остальным процессам.
> Кораблев Никита. Задача 2. Вариант 23. Итеративные методы (Зейделя).

- tasks/task_3/sadikov_d_radix_sort_batcher_merge/CMakeLists.txt
- tasks/task_3/sadikov_d_radix_sort_batcher_merge/main.cpp
- tasks/task_3/sadikov_d_radix_sort_batcher_merge/radix_sort_batcher_merge.cpp
- tasks/task_3/sadikov_d_radix_sort_batcher_merge/radix_sort_batcher_merge.h
Сначала производится деление массива пополам. Обе части сортируются поразрядной сортировкой. Затем части сливаются вместе слиянием Бэтчера
> Садиков Дамир. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

- tasks/task_1/vasyliev_i_lex_order/CMakeLists.txt
- tasks/task_1/vasyliev_i_lex_order/lex_order.cpp
- tasks/task_1/vasyliev_i_lex_order/lex_order.h
- tasks/task_1/vasyliev_i_lex_order/main.cpp
Необходимо лексикографически сравнить строки - написать параллельный аналог strcmp
> Васильев Иван. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.

- tasks/task_2/vasyliev_i_topology_rule/CMakeLists.txt
- tasks/task_2/vasyliev_i_topology_rule/main.cpp
- tasks/task_2/vasyliev_i_topology_rule/topology_rule.cpp
- tasks/task_2/vasyliev_i_topology_rule/topology_rule.h
Нужно было с помощью send и recv сымитировать передачу данных в топологии Линейка
> Васильев Иван. Задача 2. Вариант 10. Линейка.

- tasks/task_3/kazantsev_e_trapezoid_indegral/CMakeLists.txt
- tasks/task_3/kazantsev_e_trapezoid_indegral/main.cpp
- tasks/task_3/kazantsev_e_trapezoid_indegral/trapezoid_integral.cpp
- tasks/task_3/kazantsev_e_trapezoid_indegral/trapezoid_integral.h
В начале кода определены несколько классов, каждый из которых представляет определенную функцию, для которой будет вычисляться интеграл. 
Классы PiIntegral, FirstIntegral, SecondIntegral и ThirdIntegral представляют различные функции, для которых будет вычисляться интеграл. 
Каждый из этих классов содержит метод CalculateFunc, который вычисляет значение функции в заданной точке.
Затем определена функция CalculateTrapezoidIntegral, которая вычисляет интеграл методом трапеций для заданной функции, нижнего и верхнего пределов интегрирования, количества сегментов и диапазона точек, для которых будет вычисляться интеграл.
Функция TrapezoidIntegralSequential вычисляет интеграл последовательно, вызывая CalculateTrapezoidIntegral для всего диапазона точек.
Функция TrapezoidIntegralParallel …
> Казанцев Евгений Задача 3. Вариант 8. "Вычисление многомерных интегралов  метод трапеций.

- tasks/task_3/soloninko_a_moors_algorithm/CMakeLists.txt
- tasks/task_3/soloninko_a_moors_algorithm/main.cpp
- tasks/task_3/soloninko_a_moors_algorithm/moore.cpp
- tasks/task_3/soloninko_a_moors_algorithm/moore.h
Дан граф и необходимо с помощью алгоритма Беллмана-Мура найти кратчайшие пути от нулевой вершины до всех вершин в данном графе. 
Алгоритм заключается в следующем:
1. Инициализируем расстояние от исходной вершины до всех остальных, как бесконечные, а расстояние до самой исходной примем равным нулю. 
2. На этом шаге вычисляем самые короткие расстояния. Выполняем шаги `size - 1` раз, где `size` - число вершин в графе. Производим следующие действия для каждого ребра v - u: если `dist[v] > dist[u] + вес ребра u - v`, то обновляем `dist[v]`, где `dist[v] > dist[u] + вес ребра u - v`
3. Далее выясняем, есть ли в графе цикл с отрицательным весом для этого выполняем `size` раз следующее: если `dist[v] > dist[u] + вес ребра u - v`, то сообщаем, что в графе присутствует цикл отрицательного веса.
>  Солонинко Андрей. Задача 3. Вариант 23. Поиск кратчайших путей из одной вершины (алгоритм Мура).

- tasks/task_2/shubin_m_scatter/CMakeLists.txt
- tasks/task_2/shubin_m_scatter/custom_scatter.cpp
- tasks/task_2/shubin_m_scatter/custom_scatter.h
- tasks/task_2/shubin_m_scatter/main.cpp
Задача заключается в реализации передачи от одного ко всем (scatter), подобно таковому в стандартном MPI. Идея такой передачи сообщений состоит в том, что один процесс, имея последовательность значений (например, массив), рассылает всем остальным процессам части имеющейся последовательности значений. В созданной реализации происходит рассылка частей равных размеров, как в функции `MPI_Scatter`. Для проверки правильности рассылки были написаны функции, вычисляющие сумму вектора для типов данных `int`, `float` и `double`. При сравнении времени исполнения было замечено, что соотношение времени исполнения написанной функции и стандартной реализации варьируется, но не превосходит 50% как в сторону написанной функции, так и в сторону стандартной реализации.
(Переоткрыл из-за неправильного …
> Шубин Михаил. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter).

- tasks/task_1/benduyzhko_min_elements/CMakeLists.txt
- tasks/task_1/benduyzhko_min_elements/main.cpp
- tasks/task_1/benduyzhko_min_elements/min_elements.cpp
- tasks/task_1/benduyzhko_min_elements/min_elements.h
Минимальное значение элементов вектора
> Бендюжко Татьяна. Задача 1. Вариант 4. Минимальное значение элементов вектора.

- tasks/task_2/smirnov_l_broadcast/CMakeLists.txt
- tasks/task_2/smirnov_l_broadcast/broadcast.cpp
- tasks/task_2/smirnov_l_broadcast/broadcast.h
- tasks/task_2/smirnov_l_broadcast/main.cpp
broadcast - рассылка от одного процесса(корня) всем остальным процессам в виде бинарного дерева. Данные передаются с помощью дерева, где каждый узел имеет родителя и двух потомков, листья имеют только родителей, а корень - только потомков. Используются функции MPI_Send и MPI_Recv и передавать массив или вектор данных можно как типа Int, Double, так и Float.
> Смирнов Леонид. Задача 2. Вариант 5. Передача от одного всем (broadcast)

- tasks/task_3/volodin_e_convex_hull_binary_image/CMakeLists.txt
- tasks/task_3/volodin_e_convex_hull_binary_image/chbi.cpp
- tasks/task_3/volodin_e_convex_hull_binary_image/chbi.h
- tasks/task_3/volodin_e_convex_hull_binary_image/main.cpp
В программе представлены две реализации: последовательная и параллельная.
Функция `getConvexHullSeq` реализует последовательную версию. На вход, в виде двумерного массива, принимается изображение. В этом изображении ищутся все компоненты и покомпонентно строится выпуклая оболчка. На выходе получаем общую последовательность точек, составляющих выпуклую оболочку каждой компоненты в отдельности. Для разделения точек, относящихся к разным выпуклым оболочкам в конце каждой подпоследовательности ставится завершающий элемент - `-1`.
Функция `getConvexHullPar` реализует параллельную версию. На вход, в виде двумерного массива, также принимается изображение. Сначала основной процесс ищет в этом изображении все компоненты. Затем каждый из процессов узнает, сколько компонент в изображении, и, если …
> Володин Евгений. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.

- tasks/task_2/kruglov_a_allreduce/CMakeLists.txt
- tasks/task_2/kruglov_a_allreduce/allreduce.cpp
- tasks/task_2/kruglov_a_allreduce/allreduce.h
- tasks/task_2/kruglov_a_allreduce/main.cpp
Allreduce применяет выбранную операцию к данным входного буфера всех процессов коммуникатора и сохраняет результат в буфере каждого процесса. myAllreduce имеет тот же прототип, что и MPI_Allreduce и реализован только с помощью MPI_Send и MPI_Recv. В результате исследования выяснилось, что MPI_Allreduce работает в среднем в  2-3 раза быстрее, чем myAllreduce.
> Круглов Алексей. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce).

- tasks/task_3/kasimtcev_block_linear_filtering/CMakeLists.txt
- tasks/task_3/kasimtcev_block_linear_filtering/block_partit.cpp
- tasks/task_3/kasimtcev_block_linear_filtering/block_partit.h
- tasks/task_3/kasimtcev_block_linear_filtering/main.cpp
Алгоритм линейной фильтрации отображений блочным разбиением является эффективным методом анализа изображений, позволяющим значительно сократить вычислительную нагрузку.
Применение фильтра осуществляется путем применения ядра Гаусса к каждому пикселю изображения. Ядро Гаусса представляет собой двумерную матрицу значений, которая сглаживает окружающие пиксели на основе гауссовского распределения весов.
> Касимцев Роман. Задача 3. Вариант 28. Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3.

- tasks/task_2/moiseev_n_linear_topology/CMakeLists.txt
- tasks/task_2/moiseev_n_linear_topology/linear_topology.cpp
- tasks/task_2/moiseev_n_linear_topology/linear_topology.h
- tasks/task_2/moiseev_n_linear_topology/main.cpp
Топология сетей передачи данных "Кольцо" - это топология локальной сети, в которой рабочие станции или компьютеры подключены только с двумя соседними (с предыдущим и последующим).  Программа пересылает между узлами целочисленное значение и проверяет его на корректность после получения.
> Моисеев Никита. Задача 2. Вариант 10. Топология сетей передачи данных "Линейка".

- tasks/task_3/moiseev_n_moors/CMakeLists.txt
- tasks/task_3/moiseev_n_moors/main.cpp
- tasks/task_3/moiseev_n_moors/moors.cpp
- tasks/task_3/moiseev_n_moors/moors.h
Необходимо с помощью алгоритма Беллмана-Мура найти кратчайшие пути от нулевой вершины до всех вершин в данном графе.
> Моисеев Никита. Задача 3. Вариант 23. Поиск кратчайших путей из одной вершины (алгоритм Мура).

- tasks/task_3/safarov_n_int_radix_sort_simple_merge/CMakeLists.txt
- tasks/task_3/safarov_n_int_radix_sort_simple_merge/int_radix_sort_simple_merge.cpp
- tasks/task_3/safarov_n_int_radix_sort_simple_merge/int_radix_sort_simple_merge.h
- tasks/task_3/safarov_n_int_radix_sort_simple_merge/main.cpp
Цель данной лабораторной работы — реализовать алгоритм поразрядной сортировки для целых чисел с простым слиянием. В приведённом ниже коде была реализована последовательная (radixSortWithSimpleMergeSequential()) и параллельная (radixSortWithSimpleMergeParallel()) версии алгоритма. Кроме того, здесь присутствует функция generateRandomVector(), которая генерирует вектор, заполненный случайными целыми числами. Функция radixSortWithSimpleMergeParallel() принимает вектор целых чисел и размер этого вектора sizeOfVector, который указывает на количество элементов в входном векторе. Процедура разделения и слияния данных происходит следующим образом:
1. MPI_Comm_size() и MPI_Comm_rank(). Получение общего количества процессов (size) и ранга текущего процесса (rank) в группе MPI.
2. Разделение данных. …
> Сафаров Нурлан. Задача 3. Вариант 18. Поразрядная сортировка для целых чисел с простым слиянием.

- tasks/task_3/smirnova_d_monte_carlo_multiple_integration/CMakeLists.txt
- tasks/task_3/smirnova_d_monte_carlo_multiple_integration/main.cpp
- tasks/task_3/smirnova_d_monte_carlo_multiple_integration/monte_carlo_multiple_integration.cpp
- tasks/task_3/smirnova_d_monte_carlo_multiple_integration/monte_carlo_multiple_integration.h
Вычисление многомерных интегралов методом Монте-Карло.
Функция Monte_Carlo_Multiple_Integration представляет последовательный метод Монте-Карло для вычисления интеграла от функции f в многомерном пространстве, ограниченном границами a и b. Интеграл вычисляется путем генерации случайных точек и применения функции f к этим точкам. Результат вычисляется как среднее значение функции f на точках, умноженное на объем гиперкуба.
Функция Monte_Carlo_Multiple_Integration_Parallel использует параллельные вычисления для распределения между различными процессами. Каждый процесс генерирует случайные точки и вычисляет локальный результат, затем все локальные результаты суммируются с использованием функции MPI_Reduce, чтобы получить общий результат на процессе с рангом 0. Конечный результат вычисляется …
> Смирнова Дарья. Задача 3. Вариант 10. Вычисление многомерных интегралов методом Монте-Карло.

- tasks/task_2/smirnova_d_simple_iterations/CMakeLists.txt
- tasks/task_2/smirnova_d_simple_iterations/main.cpp
- tasks/task_2/smirnova_d_simple_iterations/simple_iterations.cpp
- tasks/task_2/smirnova_d_simple_iterations/simple_iterations.h
Метод простой итерации.
Код содержит функции для генерации случайной матрицы размером size × (size + 1) — generate_random_Matrix. Is_equal — проверяет, равны ли векторы с точностью 1e-4. simple_iterations — реализует алгоритм простой итерации для решения системы линейных уравнений, выполняет вычисления для каждого процесса, в том числе и MPI-операции для сбора, сдвига данных и вычисления новых приближений. get_result — разделяет данные между процессами и выполняет метод простой итерации параллельно.
> Смирнова Дарья. Задача 2. Вариант 24. Метод простой итерации.

- tasks/task_2/borisov_s_grid_torus_topology/CMakeLists.txt
- tasks/task_2/borisov_s_grid_torus_topology/grid_torus_topology.cpp
- tasks/task_2/borisov_s_grid_torus_topology/grid_torus_topology.h
- tasks/task_2/borisov_s_grid_torus_topology/main.cpp
Задача состояла в реализации топологии сетей передачи данных типа "Решетка-тор", используя  `MPI_Send` и `MPI_Recv`.
> Борисов Савелий. Задача 2. Вариант 13. Решетка-тор.

- tasks/task_2/ryabkov_v_vertical_strip/CMakeLists.txt
- tasks/task_2/ryabkov_v_vertical_strip/main.cpp
- tasks/task_2/ryabkov_v_vertical_strip/strip_vertical_scheme.cpp
- tasks/task_2/ryabkov_v_vertical_strip/strip_vertical_scheme.h
Данная лабораторная работа реализует ленточную вертикальную схему.
Функция начинается с проверки, что количество столбцов матрицы A (A_columns) равно количеству строк матрицы B (B_rows). Если это условие не выполняется, функция выбрасывает исключение.
Затем функция использует функции MPI для определения размера коммуникатора (MPI_Comm_size) и ранга процесса (MPI_Comm_rank). Это необходимо для определения, сколько процессов участвует в параллельных вычислениях и их идентификации.
Размер каждой "полосы" данных (strip) определяется как A_columns / world_size. Если есть остаток от деления, он добавляется к последней полосе. Эта полоса данных затем рассылается между процессами с использованием функции MPI_Scatter.
Каждый процесс выделяет временные массивы strip и local_vector для хранения …
> Рябков Владислав. Задача 2. Вариант 16. Ленточная вертикальная схема.

- tasks/task_3/ryabkov_v_q_batcher_sort/CMakeLists.txt
- tasks/task_3/ryabkov_v_q_batcher_sort/main.cpp
- tasks/task_3/ryabkov_v_q_batcher_sort/q_batcher_sort.cpp
- tasks/task_3/ryabkov_v_q_batcher_sort/q_batcher_sort.h
Данная лабораторная работа реализует быструю сортировку с четно-нечетными слияниями Бэтчера.
Вычисляется размер "куска" данных для каждого процесса. Предполагается, что size - это общее количество элементов данных, которые нужно отсортировать.
Создается вектор chunk, который будет хранить часть данных для каждого процесса.
Создается вектор result, который будет содержать отсортированный результат после объединения отсортированных частей.
Функция Scatter используется для отправки данных от процесса с рангом 0 (rank == 0) ко всем остальным процессам. Каждый процесс получает свою часть данных в вектор chunk для последующей сортировки.
Выполняется последовательная сортировка своего куска данных на каждом процессе с использованием функции SeqQuickSort().
Если процесс не с рангом 0, то он …
> Рябков Владислав. Задача 3. Вариант 15. Быстрая сортировка с четно-нечетным слиянием Бэтчера.

- tasks/task_3/musaev_i_matrix_double_crs/CMakeLists.txt
- tasks/task_3/musaev_i_matrix_double_crs/main.cpp
- tasks/task_3/musaev_i_matrix_double_crs/matrix_double_crs.cpp
- tasks/task_3/musaev_i_matrix_double_crs/matrix_double_crs.h
Разреженная матрица представляет собой матрицу, большая часть элементов которой равна нулю, для её хранения я использую по задаче формат CRS и тип данных double
CRS для разреженных матриц хранит значения матрицы, её столбцы и информацию о начале строк. Это позволяет уменьшить объем памяти, необходимой для хранения разреженной матрицы, и ускорить операции умножения и другие операции
> Мусаев Ильгар. Задача 3. Вариант 4. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – строковый (CRS).

- tasks/task_2/sredneva_a_hypercube/CMakeLists.txt
- tasks/task_2/sredneva_a_hypercube/hypercube.cpp
- tasks/task_2/sredneva_a_hypercube/hypercube.h
- tasks/task_2/sredneva_a_hypercube/main.cpp
Реализована топология сетей передачи данных "Гиперкуб". 
В зависимости от количества процессов строится матрица смежности sm_matrix(), далее ищется кратчайший путь между выбранными процессами с помощью алгоритма поиска в ширину, который реализован в функции bfs(). В функции send_data_hypercube() с помощью MPI_Send и MPI_Recv передаются данные между выбранными процессами по кратчайшему пути.
> Среднева Анастасия. Задача 2. Вариант 14. Гиперкуб.

- tasks/task_2/martynov_a_sleeping_hairdresser/main.cpp
- tasks/task_2/martynov_a_sleeping_hairdresser/sleeping_mans.cpp
- tasks/task_2/martynov_a_sleeping_hairdresser/sleeping_mans.h
Если несколько желающих воспользоваться Брадобрея. Брадобрей сидит в своем кресле и спит. Если в парикмахерскую приходит клиент, он должен разбудить брадобрея. Если клиент приходит и видит, что брадобрей занят, он либо садится на стул (если есть место), либо уходит (если места нет). Необходимо запрограммировать брадобрея и посетителей так, чтобы избежать состояния конфликтов.
> Мартынов Александр. Задача 2. Вариант 4. Задача «Спящий брадобрей»

- tasks/task_1/makhinya_d_rect_integration/CMakeLists.txt
- tasks/task_1/makhinya_d_rect_integration/main.cpp
- tasks/task_1/makhinya_d_rect_integration/rect_integration.cpp
- tasks/task_1/makhinya_d_rect_integration/rect_integration.h
Интегрирование – метод прямоугольников
> Махиня Данил. Задача 1. Вариант 19. Интегрирование – метод прямоугольников

- tasks/task_3/lesnikov_glob_opt_char_par/CMakeLists.txt
- tasks/task_3/lesnikov_glob_opt_char_par/glob_opt_char_par.cpp
- tasks/task_3/lesnikov_glob_opt_char_par/glob_opt_char_par.h
- tasks/task_3/lesnikov_glob_opt_char_par/main.cpp
Источник - https://www.mathnet.ru/links/e6dce3044a9b34c6cf53f651c74b28c1/tmf9159.pdf
АГП позволяет находить абсолютный минимум функции на сетке и основан на
вероятностном подходе. На основе набора известных значений функции в точках
сетки ищется интервал между соседними точками, на котором абсолютный минимум
наиболее вероятен. На этом интервале берется точка, соответствующая математическому ожиданию положения минимума, вычисляется значение функции в ней (см.
ниже формулу (4)). Точка добавляется в список известных значений, и происходит переход к следующей итерации. Алгоритм останавливается, когда расстояние
между точками отрезка последовательных итераций становится меньше заданного
значения.
Параллельный алгоритм:
На каждой итерации просчитываем количество нужных процессов и через …
> Лесников Никита. Задача 3. Вариант 13. Многошаговая схема решения двумерных задач глобальной оптимизации.  Распараллеливание по характеристикам.

- tasks/task_3/shmelev_i_horizontal_gauss_filter/CMakeLists.txt
- tasks/task_3/shmelev_i_horizontal_gauss_filter/horizontal_gauss_filter.cpp
- tasks/task_3/shmelev_i_horizontal_gauss_filter/horizontal_gauss_filter.h
- tasks/task_3/shmelev_i_horizontal_gauss_filter/main.cpp
В данной программе мною были реализованы последовательная и параллельная версии программы, которая выполняет фильтрацию изображения с использованием фильтра Гаусса.
В параллельной версии изображение построчно разделяется между процессами. Для этого определяется количество процессов, исходное изображение разбивается на части, и каждая часть передается отдельному процессу для обработки. Это происходит с помощью функций MPI_Send и MPI_Recv, где части изображения передаются и принимаются между процессами.
Каждый процесс работает над своей частью изображения, выполняя операцию фильтрации с гауссовым фильтром через gaussian_filter_operation. После завершения обработки всех частей изображения результаты собираются в выходной вектор globalResult.
> Шмелев Иван. Задача 3. Вариант 26. Линейная фильтрация изображений (горизонтальное разбиение). Ядро Гаусса 3x3..

- .gitignore
- tasks/task_1/kashirin_a_num_of_sent/CMakeLists.txt
- tasks/task_1/kashirin_a_num_of_sent/main.cpp
- tasks/task_1/kashirin_a_num_of_sent/num_of_sent.cpp
- tasks/task_1/kashirin_a_num_of_sent/num_of_sent.h
Подсчет количества предложений в строке
> Каширин Александр. Задача 1. Вариант 25. Подсчет количества предложений в строке

- tasks/task_1/kalinin_a_lex_strings/CMakeLists.txt
- tasks/task_1/kalinin_a_lex_strings/lex_strings.cpp
- tasks/task_1/kalinin_a_lex_strings/lex_strings.h
- tasks/task_1/kalinin_a_lex_strings/main.cpp
Реализовал проверку лексикографической упорядоченности двух строк. В распараллеливании использовал MPI_Scatterv, в конце, объединил результат всех процессов и разослал и результат с помощью MPI_Allreduce
> Калинин Александр. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк

- tasks/task_2/bodrov_d_philosopher/main.cpp
- tasks/task_2/bodrov_d_philosopher/philosopher.cpp
Пофиксил тесты, теперь занимают меньше 100ms
> Обновление тестов

- tasks/task_3/khodyrev_f_simpson_method/main.cpp
> Обновление тестов.

- tasks/task_3/sokolova_d_jarvis_algorithm/CMakeLists.txt
- tasks/task_3/sokolova_d_jarvis_algorithm/jarvis_algorithm.cpp
- tasks/task_3/sokolova_d_jarvis_algorithm/jarvis_algorithm.h
- tasks/task_3/sokolova_d_jarvis_algorithm/main.cpp
Задача заключалась в реализации алгоритма Джарвиса для поиска выпуклой оболочки множества точек в двумерном пространстве. Функция consistentJarvisMarch выполняет последовательную обработку вектора точек для нахождения выпуклой оболочки. Функция parallelJarvisMarch распараллеливает алгоритм с использованием MPI, разделяя вектор точек между процессами, а затем собирая результаты для завершения алгоритма на процессе с рангом 0.
> Соколова Дарья. Задача 3. Вариант 25. Построение выпуклой оболочки – проход Джарвиса.

- tasks/task_2/dostavalov_s_bubble_sort/CMakeLists.txt
- tasks/task_2/dostavalov_s_bubble_sort/bubble_sort.cpp
- tasks/task_2/dostavalov_s_bubble_sort/bubble_sort.h
- tasks/task_2/dostavalov_s_bubble_sort/main.cpp
> Доставалов Семен. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки).

- tasks/task_1/tushentsova_k_count_mis_char/CMakeLists.txt
- tasks/task_1/tushentsova_k_count_mis_char/count_mis_char.cpp
- tasks/task_1/tushentsova_k_count_mis_char/count_mis_char.h
- tasks/task_1/tushentsova_k_count_mis_char/main.cpp
Подсчет числа несовпадающих символов двух строк
> Тушенцова Карина. Задача 1. Вариант 27. Подсчет числа несовпадающих символов двух строк.

- tasks/task_2/tushentsova_k_odd_even_sort/CMakeLists.txt
- tasks/task_2/tushentsova_k_odd_even_sort/main.cpp
- tasks/task_2/tushentsova_k_odd_even_sort/odd_even_sort.cpp
- tasks/task_2/tushentsova_k_odd_even_sort/odd_even_sort.h
Сортировка пузырьком (алгоритм чет-нечетной перестановки)
> Тушенцова Карина. Задача 2. Вариант 25. Сортировка пузырьком

- tasks/task_3/kashin_s_multiplication_of_sparse_crs_matrices/CMakeLists.txt
- tasks/task_3/kashin_s_multiplication_of_sparse_crs_matrices/main.cpp
- tasks/task_3/kashin_s_multiplication_of_sparse_crs_matrices/multiplication_of_sparse_crs_matrices.cpp
- tasks/task_3/kashin_s_multiplication_of_sparse_crs_matrices/multiplication_of_sparse_crs_matrices.h
Процессам выдаются строчки которые они вычисляют(они получают необходимые колонки и столбцы из класса CRS getCol/getRow и перемножат их) потом все строки собираются при помощи функции MPI_Gatherv в матрицу в одномерном векторе, который преобразуются в обратно в CRS в нулевом процессе.
> Кашин Степан. Задача 3. Вариант 4. Умножение разреженных матриц. Элементы типа double.  Формат хранения матрицы – строковый (CRS).

- tasks/task_1/makhinya_d_rect_integration/CMakeLists.txt
- tasks/task_1/makhinya_d_rect_integration/main.cpp
- tasks/task_1/makhinya_d_rect_integration/rect_integration.cpp
- tasks/task_1/makhinya_d_rect_integration/rect_integration.h
- tasks/task_2/makhinya_d_readers_writers/CMakeLists.txt
- tasks/task_2/makhinya_d_readers_writers/main.cpp
- tasks/task_2/makhinya_d_readers_writers/readers_writers.cpp
- tasks/task_2/makhinya_d_readers_writers/readers_writers.h
> Махиня Данил. Задача 2. Вариант 2. Задача «Читатели-Писатели»

- tasks/task_1/makhinya_d_rect_integration/CMakeLists.txt
- tasks/task_1/makhinya_d_rect_integration/main.cpp
- tasks/task_1/makhinya_d_rect_integration/rect_integration.cpp
- tasks/task_1/makhinya_d_rect_integration/rect_integration.h
- tasks/task_2/makhinya_d_readers_writers/CMakeLists.txt
- tasks/task_2/makhinya_d_readers_writers/main.cpp
- tasks/task_2/makhinya_d_readers_writers/readers_writers.cpp
- tasks/task_2/makhinya_d_readers_writers/readers_writers.h
- tasks/task_3/makhinya_d_conjugate_gradient_method/CMakeLists.txt
- tasks/task_3/makhinya_d_conjugate_gradient_method/gradient_method.cpp
- tasks/task_3/makhinya_d_conjugate_gradient_method/gradient_method.h
- tasks/task_3/makhinya_d_conjugate_gradient_method/main.cpp
Решение систем линейных уравнений методом сопряженных градиентов.
> Махиня Данил. Задача 3. Вариант 6. Решение систем линейных уравнений методом сопряженных градиентов.

- tasks/task_2/simonyan_s_allreduce/Allreduce.cpp
- tasks/task_2/simonyan_s_allreduce/Allreduce.h
- tasks/task_2/simonyan_s_allreduce/CMakeLists.txt
- tasks/task_2/simonyan_s_allreduce/main.cpp
Реализовал allreduce используя только функции Send и Recv. выполняется пересылка
массива следующих типов: MPI_INT, MPI_FLOAT, MPI_DOUBLE
> Симонян Сурен. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)

- tasks/task_3/tushentsova_k_convex_hull/CMakeLists.txt
- tasks/task_3/tushentsova_k_convex_hull/convex_hull.cpp
- tasks/task_3/tushentsova_k_convex_hull/convex_hull.h
- tasks/task_3/tushentsova_k_convex_hull/main.cpp
Построение выпуклой оболочки для компонент бинарного изображения
> Тушенцова Карина. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения

- tasks/task_2/novostroev_i_philosophers/CMakeLists.txt
- tasks/task_2/novostroev_i_philosophers/main.cpp
- tasks/task_2/novostroev_i_philosophers/philosophers.cpp
- tasks/task_2/novostroev_i_philosophers/philosophers.h
Программа моделирует взаимодействие философов, которые могут находиться в состояниях "размышление", "голод", и "еда". Философы могут совершать переходы между этими состояниями и взаимодействовать друг с другом при запросе и освобождении вилок (ресурсов).
> Новостроев Иван. Задача 2. Вариант 3. Задача «Обедающие философы».

- tasks/task_1/kistrimova_e_letter_count/CMakeLists.txt
- tasks/task_1/kistrimova_e_letter_count/letter_count.cpp
- tasks/task_1/kistrimova_e_letter_count/letter_count.h
- tasks/task_1/kistrimova_e_letter_count/main.cpp
Для подсчета числа буквенных символов в строке можно использовать следующие алгоритмы:
Однопоточный алгоритм: Пройти по каждому символу в строке с помощью цикла. Используя функцию isalpha(), проверить, является ли символ буквой. Если символ является буквой, увеличить счетчик. По окончании цикла, вернуть значение счетчика.
Многопоточный алгоритм: Разделить строку на несколько частей (количество частей равно количеству процессов). Например, для строки "abc123" можно разделить на 2 части: "abc" и "123". Обмен данными между процессами осуществляется с помощью функций send и recv. Затем собрать данные с процессов и сложить полученные значения.
Оба алгоритма должны предоставлять одинаковый результат подсчета числа буквенных символов в строке, но различаются в способе выполнения и использования …
> Кистримова Екатерина. Задача 1. Вариант 22. Подсчет числа буквенных символов в строке.

- tasks/task_2/kistrimova_e_reduce/CMakeLists.txt
- tasks/task_2/kistrimova_e_reduce/main.cpp
- tasks/task_2/kistrimova_e_reduce/my_reduce.cpp
- tasks/task_2/kistrimova_e_reduce/my_reduce.h
Дерево процессов представлено в виде бинарного дерева поиска. Данные перемещаются из самого нижнего уровня к корню дерева. При прохождении по каждому ребру с данными выполняется редукция. Данные проходят по всем путям, за исключением пути от корня дерева до root. Когда данные достигают корня дерева (исключая указанный путь), корень дерева отправляет данные к root (продолжая редукцию на каждом ребре). Таким образом, результат достигает root.
> Кистримова Екатерина. Задача 2. Вариант 6. Передача от всех одному (reduce).

- tasks/task_2/kutarin_a_ring/CMakeLists.txt
- tasks/task_2/kutarin_a_ring/main.cpp
- tasks/task_2/kutarin_a_ring/ring.cpp
- tasks/task_2/kutarin_a_ring/ring.h
Данный код реализует алгоритм передачи сообщений по кольцевой топологии с использованием библиотеки MPI. Он содержит функции для определения простоя передачи сообщений, определения номеров предыдущего и следующего процесса в кольце, а также функцию для отправки и приема сообщений между процессами.
> Кутарин Александр. Задача 2. Вариант 11. Топология сети передачи данных кольцо.

- tasks/task_3/kutarin_a_bitwise_sorting_rnumbers/CMakeLists.txt
- tasks/task_3/kutarin_a_bitwise_sorting_rnumbers/main.cpp
- tasks/task_3/kutarin_a_bitwise_sorting_rnumbers/radix_sort_batcher.cpp
- tasks/task_3/kutarin_a_bitwise_sorting_rnumbers/radix_sort_batcher.h
Данный код реализует параллельный алгоритм сортировки чисел с плавающей запятой посредством поразрядной сортировки. Он разделяет вектор чисел на две половины и отправляет их между процессорами с использованием библиотеки Boost MPI. Затем каждый процессор выполняет сортировку своей части вектора. После этого процессоры обмениваются частями вектора и выполняют симметричную перестановку элементов. В результате получается отсортированный вектор чисел.
> Кутарин Александр. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

- tasks/task_3/filatov_m_calc_integral_rec/CMakeLists.txt
- tasks/task_3/filatov_m_calc_integral_rec/calc_integral_rec.cpp
- tasks/task_3/filatov_m_calc_integral_rec/calc_integral_rec.h
- tasks/task_3/filatov_m_calc_integral_rec/main.cpp
Используя метод прямоугольников, была выполнена задача вычисления значение многомерных интегралов. Число областей интеграции, основывается на количестве разбиений интервала по каждой из переменных. Далее эти области распределяются между процессами равномерно, и каждый процесс получает свой диапазон для вычисления локального интеграла. Избыток неравномерно распределенных областей обрабатывается последним процессом. Затем локальные вычисленные интегральные значения объединяются при помощи операции свертки.
Чтобы удостовериться в правильности работы параллельного алгоритма, его необходимо сначала проверить в последовательном исполнении. Валидация результатов параллельных вычислений производится путем сравнения с выводом однопоточной версии алгоритма, применяемого к случайному набору …
> Филатов Максим. Задача 3. Вариант 7. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

- tasks/task_3/kochetov_n_conv_hull/CMakeLists.txt
- tasks/task_3/kochetov_n_conv_hull/conv_hull.cpp
- tasks/task_3/kochetov_n_conv_hull/conv_hull.h
- tasks/task_3/kochetov_n_conv_hull/main.cpp
В программе реализован алгоритм поиска выпуклой оболочки для компонент бинарного изображения. Алгоритм имеет две вариации - последовательную и параллельную. На вход ему подается матрица изображения, состоящая из нулей и единиц, где единицы представляют пиксели изображения, а нули - пиксели фона. 
В случае последовательной версии алгоритма, на первом этапе происходит маркировка компонент изображения. После чего получаем набор массивов, содержащих координаты пикселей каждой связной компоненты. Затем для каждой компоненты находится ее выпуклая оболочка. 
В случае параллельной версии алгоритма, основной процесс ищет компоненты изображения, после чего происходит деление изображения на части для каждого процесса. Каждый процесс находит выпуклые оболочки в своей части изображения, а затем …
> Кочетов Николай. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.

- tasks/task_1/nikitin_k_word_count/CMakeLists.txt
- tasks/task_1/nikitin_k_word_count/count_words.cpp
- tasks/task_1/nikitin_k_word_count/count_words.h
- tasks/task_1/nikitin_k_word_count/main.cpp
Постановка задачи: последовательный и параллельный подсчет количества слов в строке, разделяя строку на блоки и выполняя подсчет на каждом процессе, а после суммируя результаты на процессе с определённым рангом.
> Никитин Кирилл. Задача #1, 24 вариант - подсчет числа слов в строке.

- tasks/task_3/nikitin_k_dijkstra_algorithm/CMakeLists.txt
- tasks/task_3/nikitin_k_dijkstra_algorithm/dijkstra_algorithm.cpp
- tasks/task_3/nikitin_k_dijkstra_algorithm/dijkstra_algorithm.h
- tasks/task_3/nikitin_k_dijkstra_algorithm/main.cpp
В моём проекте представлен алгоритм Дейкстры для поиска кратчайших путей в графе. 
Код содержит две функции: DijkstraSeq и DijkstraParallel.
Функция DijkstraSeq реализует последовательный вариант алгоритма. Она принимает на вход граф (представленный в виде вектора), вершину-источник и размер графа. Возвращает вектор кратчайших путей от вершины-источника до всех остальных вершин.
Функция DijkstraParallel реализует параллельный вариант алгоритма. Она также принимает на вход граф, вершину-источник и размер графа. Возвращает вектор кратчайших путей от вершины-источника до всех остальных вершин. Для выполнения вычислений в параллельных потоках используется структура std::thread.
Функция processNode выполняет итерацию алгоритма для определенного диапазона вершин, указанного в аргументах start и …
> Никитин Кирилл. Задача №3. Вариант 22 - поиск кратчайших путей из одной вершины (алгоритм Дейкстры).

- tasks/task_1/trubin_a_sum_of_vector_elements/CMakeLists.txt
- tasks/task_1/trubin_a_sum_of_vector_elements/main.cpp
- tasks/task_1/trubin_a_sum_of_vector_elements/sum_vector.cpp
- tasks/task_1/trubin_a_sum_of_vector_elements/sum_vector.h
Производится подсчёт суммы элементов вектора.
> Трубин Артем. Задача 1. Вариант 1. Сумма элементов вектора.

- tasks/task_2/trubin_a_barber/CMakeLists.txt
- tasks/task_2/trubin_a_barber/main.cpp
- tasks/task_2/trubin_a_barber/sleeping_barber.cpp
- tasks/task_2/trubin_a_barber/sleeping_barber.h
Парикмахерская с одним парикмахером, у которого есть своё рабочее место и приёмная с множеством стульев. Когда парикмахер заканчивает обслуживание клиента, он проверяет, есть ли ожидающие клиенты в приёмной. Если таковые имеются, он приглашает одного из них и приступает к обслуживанию. Если нет ожидающих клиентов, он возвращается к своему рабочему месту и отдыхает. Каждый новый клиент наблюдает за парикмахером. Если парикмахер отдыхает, клиент будит его и садится в кресло. Если же парикмахер занят, клиент отправляется в приёмную. В случае, если в приёмной свободны стулья, клиент садится и ждёт своей очереди. В противном случае клиент покидает место.
> Трубин Артем. Задача 2. Вариант 4. Задача «Спящий брадобрей».

- tasks/task_3/trubin_a_bin_img/CMakeLists.txt
- tasks/task_3/trubin_a_bin_img/bin_img.cpp
- tasks/task_3/trubin_a_bin_img/bin_img.h
- tasks/task_3/trubin_a_bin_img/main.cpp
есть бинарное изображение, где черные области представляют объекты (такие как лица на фотографии, предметы на скане, и т. д.), а белые области - фон. Задача заключается в том, чтобы присвоить уникальные метки различным связным областям в изображении.
> Трубин Артем. Задача 3. Вариант 31. Маркировка компонент на бинарном изображении  (черные области соответствуют объектам, белые – фону).

- tasks/task_1/gontsov_r_integrate_trapez/CMakeLists.txt
- tasks/task_1/gontsov_r_integrate_trapez/integrate_trapez.cpp
- tasks/task_1/gontsov_r_integrate_trapez/integrate_trapez.h
- tasks/task_1/gontsov_r_integrate_trapez/main.cpp
Мой код представляет собой две функции для вычисления определенного интеграла методом трапеций: getSequentialIntegration и getParallelIntegration.
getSequentialIntegration: Вычисляет определенный интеграл для заданной функции f на интервале [a, b] с использованием метода трапеций. Разбивает интервал на n частей и вычисляет приближенное значение интеграла.
getParallelIntegration: Распараллеливает вычисление определенного интеграла методом трапеций для заданной функции f на интервале [a, b] с использованием библиотеки MPI (Message Passing Interface). Использует метод разделения интервала между процессами MPI.
> Гонцов Роман. Задача 1. Вариант 20 - Интегрирование – метод трапеций

- tasks/task_2/gontsov_r_star/CMakeLists.txt
- tasks/task_2/gontsov_r_star/main.cpp
- tasks/task_2/gontsov_r_star/star.cpp
- tasks/task_2/gontsov_r_star/star.h
Данный код представляет собой функцию send_data, реализованную с использованием библиотеки Boost.MPI, предназначенной для работы с MPI (Message Passing Interface). Функция предназначена для передачи данных между процессами MPI, обеспечивая правильную передачу данных в зависимости от роли каждого процесса (отправитель, получатель, корневой процесс).
> Гонцов Роман. Задача 2. Вариант 12 - Звезда

- tasks/task_3/gontsov_r_monte_carlo_integrate/CMakeLists.txt
- tasks/task_3/gontsov_r_monte_carlo_integrate/main.cpp
- tasks/task_3/gontsov_r_monte_carlo_integrate/monte_carlo_integrate.cpp
- tasks/task_3/gontsov_r_monte_carlo_integrate/monte_carlo_integrate.h
Данный код представляет собой две функции для численного интегрирования методом Монте-Карло с использованием стандартной библиотеки C++ и многопоточности: getIntegralMonteCarlo и getIntegralMonteCarloStd.
Функция getIntegralMonteCarlo:
Эта функция вычисляет приближенное значение определенного интеграла функции f в многомерном пространстве методом Монте-Карло.
Функция getIntegralMonteCarloStd:
Эта функция выполняет параллельное вычисление интеграла методом Монте-Карло с использованием стандартной библиотеки C++ и многопоточности. Входные параметры аналогичны функции getIntegralMonteCarlo. Для распараллеливания используются стандартные средства многопоточности из библиотеки <thread>.
> Гонцов Роман. Задача 3. Вариант 10 - Вычисление многомерных интегралов методом Монте-Карло.

- tasks/task_3/chuvashov_a_the_graham_passage/CMakeLists.txt
- tasks/task_3/chuvashov_a_the_graham_passage/main.cpp
- tasks/task_3/chuvashov_a_the_graham_passage/the_graham_passage.cpp
- tasks/task_3/chuvashov_a_the_graham_passage/the_graham_passage.h
В данной работе реализован алгоритм Грэхема для множество сгенерированных точек. Суть задачи - построить выпуклую оболочку на изображении по координатам и вернуть координаты точек оболочки. Задача реализована с использованием параллельного программирования.
> Чувашов Андрей. Задача 3. Вариант 24. Построение выпуклой оболочки - проход Грэхема.

- tasks/task_1/platonova_m_min_matrix_rows/CMakeLists.txt
- tasks/task_1/platonova_m_min_matrix_rows/main.cpp
- tasks/task_1/platonova_m_min_matrix_rows/min_matrix_rows.cpp
- tasks/task_1/platonova_m_min_matrix_rows/min_matrix_rows.h
Мой код содержит две функции для нахождения индексов минимальных элементов в каждой строке матрицы. Одна функция выполняет это параллельно с использованием библиотеки Boost.MPI, а вторая - последовательно.
getParallelMin(std::vector<int> glob_matr, int m, int n): Находит индексы минимальных элементов в каждой строке матрицы параллельно с использованием библиотеки Boost.MPI. Каждый процесс MPI получает подматрицу и находит минимальный элемент в каждой из своих строк. Затем результаты собираются на процессе с рангом 0.
getSequentialMin(std::vector<int> matr, int m): Находит индексы минимальных элементов в каждой строке матрицы последовательно. Проходит по каждой строке матрицы и находит минимальный элемент в каждой из них.
> Платонова Мария. Задача 1. Вариант 17 - Нахождение минимальных значений по строкам матрицы

- tasks/task_2/platonova_m_scatter_method/CMakeLists.txt
- tasks/task_2/platonova_m_scatter_method/main.cpp
- tasks/task_2/platonova_m_scatter_method/scatter.cpp
- tasks/task_2/platonova_m_scatter_method/scatter.h
Этот код содержит реализацию функций для распределения данных с использованием собственной версии метода Scatter в MPI.
MyScatter: Это функция, которая реализует метод Scatter для распределения данных от корневого процесса (указанного параметром root) всем остальным процессам в коммуникаторе MPI. Функция использует MPI_Send и MPI_Recv для передачи данных. Если процесс является корневым (rank == root), то данные разбиваются и отправляются каждому процессу; если процесс не является корневым, то он принимает данные от корневого процесса.
randomVector: Генерирует случайный вектор целых чисел заданного размера (sizeVec), где каждый элемент находится в пределах от minValue до maxValue.
В целом, код предоставляет простую реализацию Scatter для MPI и функцию для генерации случайных векторов.
> Платонова Мария. Задача 2. Вариант 8 - Обобщенная передача от одного всем (scatter)

- tasks/task_3/platonova_m_sobel_edge/CMakeLists.txt
- tasks/task_3/platonova_m_sobel_edge/main.cpp
- tasks/task_3/platonova_m_sobel_edge/sobel_edge.cpp
- tasks/task_3/platonova_m_sobel_edge/sobel_edge.h
Этот код содержит реализацию операции обработки изображений с использованием оператора Собеля для выделения границ. Кроме того, предоставлены функции для создания изображений (белого, черного и случайного) и функции, реализующие обработку изображений с использованием стандартных и многопоточных методов.
Общий смысл кода заключается в реализации операции Собеля для выделения границ на изображениях, а также в предоставлении функционала для создания различных типов изображений и их обработки.
> Платонова Мария. Задача 3. Вариант 29 - Выделение ребер на изображении с использованием оператора Собеля.

- tasks/task_2/bakhtiarov_a_broadcast/CMakeLists.txt
- tasks/task_2/bakhtiarov_a_broadcast/broadcast.cpp
- tasks/task_2/bakhtiarov_a_broadcast/broadcast.h
- tasks/task_2/bakhtiarov_a_broadcast/main.cpp
Broadcast - это операция передачи данных от одного процесса (корня) всем остальным процессам с использованием бинарного дерева. При выполнении операции данные передаются по дереву, где каждый узел имеет родителя и двух потомков. Листья имеют только родителей, а корень - только потомков. Для реализации данной операции используются функции MPI_Send и MPI_Recv, и массив или вектор данных можно передавать как тип Int, Double или Float.
> Бахтияров Александр. Задача 2. Вариант 5. Передача от одного всем (broadcast)

- tasks/task_3/bakhtiarov_a_multiplication_of_sparse_crs_matrices/CMakeLists.txt
- tasks/task_3/bakhtiarov_a_multiplication_of_sparse_crs_matrices/main.cpp
- tasks/task_3/bakhtiarov_a_multiplication_of_sparse_crs_matrices/multiplication_of_sparse_crs_matrices.cpp
- tasks/task_3/bakhtiarov_a_multiplication_of_sparse_crs_matrices/multiplication_of_sparse_crs_matrices.h
Процессам выделяются строки для вычислений, которые они выполняют, получая необходимые столбцы и строки из класса CRS с помощью методов getCol/getRow, а затем перемножают их. Затем все строки собираются в матрицу при помощи функции MPI_Gatherv и помещаются в одномерный вектор, который затем преобразуется обратно в CRS в нулевом процессе.
> Бахтияров Александр. Задача 3. Вариант 4. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – строковый (CRS)

- tasks/task_1/vetoshnikova_k_vector_dot_product/CMakeLists.txt
- tasks/task_1/vetoshnikova_k_vector_dot_product/main.cpp
- tasks/task_1/vetoshnikova_k_vector_dot_product/vector_dot_product.cpp
- tasks/task_1/vetoshnikova_k_vector_dot_product/vector_dot_product.h
- tasks/task_2/vetoshnikova_k_bubble_sort/CMakeLists.txt
- tasks/task_2/vetoshnikova_k_bubble_sort/bubble_sort.cpp
- tasks/task_2/vetoshnikova_k_bubble_sort/bubble_sort.h
- tasks/task_2/vetoshnikova_k_bubble_sort/main.cpp
В данном алгоритме сравнивается каждый нечётный элемент массива с последующим и если они оказываются в неправильном порядке, то элементы меняются местами. То же самое делается с чётными элементами. При реализации параллельной версии алгоритма использовались функции MPI_Scatterv(), MPI_Gatherv().
> Ветошникова Екатерина. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки).

- tasks/task_1/shemyakina_a_most_different_neighbor_elements/CMakeLists.txt
- tasks/task_1/shemyakina_a_most_different_neighbor_elements/main.cpp
- tasks/task_1/shemyakina_a_most_different_neighbor_elements/most_different_neighbor_elements.cpp
- tasks/task_1/shemyakina_a_most_different_neighbor_elements/most_different_neighbor_elements.h
Наша задача - найти наиболее отличающиеся по значению соседние элементы вектора. В программе реализовывается сравнение соседних элементов вектора и выбор таких, которые имеют максимальную по модулю разность. Происходит разбиение вектора на части и исследование каждой отдельно, учтен тот факт, что пары соседей, находящихся на границах каждой части, не должны быть пропущены: к каждой части(массиву), кроме последнего непустого, добавляется один элемент из начала следующего массива. Использована функция `MPI_REDUCE`, которая объединяет элементы входного буфера каждого процесса в нашем векторе.
> Шемякина Алеся. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.

- tasks/task_1/loginov_m_count_smb_str/CMakeLists.txt
- tasks/task_1/loginov_m_count_smb_str/count_smb_str.cpp
- tasks/task_1/loginov_m_count_smb_str/count_smb_str.h
- tasks/task_1/loginov_m_count_smb_str/main.cpp
Реализовал параллельный подсчет частоты символа в строке, используя MPI_Scatterv
> Логинов Максим. Задача 1. Вариант 23. Подсчет частоты символа в строке

- tasks/task_3/korablev_n_matrix_multiplication/CMakeLists.txt
- tasks/task_3/korablev_n_matrix_multiplication/main.cpp
- tasks/task_3/korablev_n_matrix_multiplication/matrix_mult.cpp
- tasks/task_3/korablev_n_matrix_multiplication/matrix_mult.h
Для подготовки данных на отправку процессорам для каждого нам нужно выбирать k, чтобы им не поступили к одни и тем же данные для вычислений. Данных выстраиваются в одномерный массив и отправляются процессам с помощью scatterv.
Каждый процесс получает свои подматрицы исходных матриц. 
Затем процесс перемножает их и прибавляет результат к своей итоговой матрице. После этого левая матрица циклически передается влево, а правая вверх по двумерной сетке процессов. Так продолжается N раз. где N * N - число процессов. Затем результаты передаются корневому процессу с помощью gatherv и из них формируется конечная матрица.
> Кораблев Никита. Задача 3. Вариант 1. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона.

- tasks/task_1/kuznetsov_m_min_value_in_matrix/CMakeLists.txt
- tasks/task_1/kuznetsov_m_min_value_in_matrix/main.cpp
- tasks/task_1/kuznetsov_m_min_value_in_matrix/min_value_in_matrix.cpp
- tasks/task_1/kuznetsov_m_min_value_in_matrix/min_value_in_matrix.h
Цель лабораторной работы представляет собой параллельную реализацию поиска минимального значения в массиве matrix. Она использует библиотеку MPI для обеспечения взаимодействия между различными процессами.
rank: Номер текущего процесса.
part: Размер подмассива, который каждый процесс будет обрабатывать. Вычисляется как size / process_num.
min_values: Массив для хранения минимальных значений, вычисленных каждым процессом.
MPI_Comm_rank(MPI_COMM_WORLD, &rank): Получение номера текущего процесса.
MPI_Status status: Структура для хранения информации о статусе MPI операций.
Если rank равен 0, то процесс с рангом 0 разбивает исходный массив на части и отправляет каждому из процессов свою часть массива с использованием MPI_Send.
Каждый процесс, отличный от 0, получает свою часть данных с …
> Кузнецов Михаил. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.

- tasks/task_2/shemyakina_a_star_topology/CMakeLists.txt
- tasks/task_2/shemyakina_a_star_topology/main.cpp
- tasks/task_2/shemyakina_a_star_topology/star_topology.cpp
- tasks/task_2/shemyakina_a_star_topology/star_topology.h
В программе реализовывается топология "Звезда", в которой каждое устройство в сети подключается к центральному устройству(master) с помощью отдельного кабеля. Центральное устройство, коммутатор, выполняет функцию контроля и передачи данных между подключенными устройствами. Данная виртуальная топология реализована с помощью функций  `MPI_Send` и `MPI_Recv`.
> Шемякина Алеся. Задача 2. Вариант 12. Топология сети передачи данных "Звезда".

- tasks/task_3/shemyakina_a_strassen_algorithm/CMakeLists.txt
- tasks/task_3/shemyakina_a_strassen_algorithm/main.cpp
- tasks/task_3/shemyakina_a_strassen_algorithm/strassen_algorithm.cpp
- tasks/task_3/shemyakina_a_strassen_algorithm/strassen_algorithm.h
Данная программа реализовывает алгоритм Штрассена по умножению матриц. Алгоритм сводит все матрицы к специальному, блочному виду, далее вычисляются несколько вспомогательных матриц, а затем из них с помощью сложений формируется итоговая матрица. Алгоритм реализовывается в функции `StrassenAlgorinhm`.
> Шемякина Алеся. Задача 3. Вариант 3. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

- tasks/task_1/lebedeva_k_words_count/CMakeLists.txt
- tasks/task_1/lebedeva_k_words_count/main.cpp
- tasks/task_1/lebedeva_k_words_count/words_count.cpp
- tasks/task_1/lebedeva_k_words_count/words_count.h
Программа для подсчета числа слов в строке с использованием MPI предполагает, что текстовая строка делится между различными процессами, каждый из которых отвечает за подсчет слов в своей части строки. MPI используется для распараллеливания подсчета слов. В конце выполнения, результаты собираются и выводится общее количество слов.
> Лебедева Ксения. Задача 1. Вариант 24. Подсчет числа слов в строке. 

- tasks/task_1/vetoshnikova_k_vector_dot_product/CMakeLists.txt
- tasks/task_1/vetoshnikova_k_vector_dot_product/main.cpp
- tasks/task_1/vetoshnikova_k_vector_dot_product/vector_dot_product.cpp
- tasks/task_1/vetoshnikova_k_vector_dot_product/vector_dot_product.h
- tasks/task_2/vetoshnikova_k_bubble_sort/CMakeLists.txt
- tasks/task_2/vetoshnikova_k_bubble_sort/bubble_sort.cpp
- tasks/task_2/vetoshnikova_k_bubble_sort/bubble_sort.h
- tasks/task_2/vetoshnikova_k_bubble_sort/main.cpp
- tasks/task_3/vetoshnikova_k_component_marking/CMakeLists.txt
- tasks/task_3/vetoshnikova_k_component_marking/component_marking.cpp
- tasks/task_3/vetoshnikova_k_component_marking/component_marking.h
- tasks/task_3/vetoshnikova_k_component_marking/main.cpp
Необходимо найти компоненты на бинарном изображении, каждой присвоить уникальную метку. При реализации 
алгоритма использовались функции MPI_Send(), MPI_Recv(), MPI_Reduce().
> Ветошникова Екатерина. Задача 3. Вариант 31. Маркировка компонент на бинарном изображении  (черные области соответствуют объектам, белые – фону).

- tasks/task_3/kashirin_a_ccs_matrix_mult/CMakeLists.txt
- tasks/task_3/kashirin_a_ccs_matrix_mult/ccs_matrix_mult.cpp
- tasks/task_3/kashirin_a_ccs_matrix_mult/ccs_matrix_mult.h
- tasks/task_3/kashirin_a_ccs_matrix_mult/main.cpp
Реализация параллельного умножения разреженных матриц
> Каширин Александр. Задача 3. Вариант 5. Умножение разреженных матриц. Элементы типа double. Формат хранения - столбцовый(ccs)
